### ISSUE TITLE
Got can't decompress the response data that browser can decompress.

### ISSUE THREAD

**Issue by heroboy** [sindresorhus/got#1124] opened 2020-03-19 03:29 UTC
https://github.com/sindresorhus/decompress-response/issues/24

#### Describe the bug

 - Node.js version:  v13.5.0
 - OS & version:  windows

Got can't decompress the response data that browser can decompress.
See the below code.

#### Actual behavior

`GotError: incorrect header check`

#### Expected behavior

print "abc" on console
just like the browser.

#### Code to reproduce

```javascript
const zlib = require('zlib')
const http = require('http');
const got = require('got').default;
let server = http.createServer((req, res) =>
{
	console.log('request');
	res.writeHead(200, { 'Content-Type': 'text/plain', 'content-encoding': 'deflate' });
	res.end(zlib.deflateRawSync('abc'));//change to deflateSync, 'got' will work.
})
server.listen(8989, '0.0.0.0', async function ()
{
	try
	{
		let resp = await got('http://127.0.0.1:8989');
		console.log(resp.body);
	}
	catch (e)
	{
		console.log(e);
	}
});
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment] 2020-03-19 03:47
Duplicate of https://github.com/sindresorhus/got/issues/388

**Comment by sindresorhus** [comment] 2020-03-19 03:48
Browsers are more lenient to incorrect data for legacy reasons and also because they're user-facing.

**Closed by sindresorhus** 2020-03-19 03:47 UTC

**Comment by heroboy** [comment] 2020-03-19 04:04
@sindresorhus , thanks. Although it may be inconvenient. 
But I respect your decision that conform the standard.

**Comment by heroboy** [comment] 2021-09-03 12:04
hello @sindresorhus ,
according to the comment in chrome source code:
https://source.chromium.org/chromium/chromium/src/+/main:net/filter/gzip_source_stream.h;drc=ba9a4288f7440532b91f99593dc59822c7478cd3;l=24

> As specified by HTTP 1.1, with gzip encoding the content is
> wrapped with a gzip header, and with deflate encoding the content is in
> a raw, headerless DEFLATE stream.

The `deflateRaw` is the http standard.

**Comment by szmarczak** [comment] 2021-09-03 13:40
> The deflateRaw is the http standard.

The below states otherwise:

https://datatracker.ietf.org/doc/html/rfc7231#section-3.1.2.1
https://datatracker.ietf.org/doc/html/rfc7230#section-4.2.2

> The "deflate" coding is a "zlib" data format
> [...]
>      Note: Some non-conformant implementations send the "deflate"
>      compressed data without the zlib wrapper.

Again, please note:

> Browsers are more lenient to incorrect data for legacy reasons and also because they're user-facing.
