### ISSUE TITLE
Weird incompatibility between Node 14, keepAlive and cache

### ISSUE THREAD

**Issue by phawxby** [sindresorhus/got#1526] opened 2020-11-17 10:14 UTC
#### Describe the bug

When using node 14, http agent keep alive and cache, got bails with no error. Seems to be very specifically this combination of things.

```
Environment Info:
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

Got: 11.8.0
```

#### Actual behavior

```
paul@Pauls-iPad got-keyv % nvm use 14.15.1
Now using node v14.15.1 (npm v6.14.8)
paul@Pauls-iPad got-keyv % node test2.js  
Without cache or agent 400
With cache 400
With agent 400
paul@Pauls-iPad got-keyv % 
```

#### Expected behavior

```
paul@Pauls-iPad got-keyv % nvm use 12.19.0
Now using node v12.19.0 (npm v6.14.8)
paul@Pauls-iPad got-keyv % node test2.js  
Without cache or agent 400
With cache 400
With agent 400
With cache and agent 400
Done
```

#### Code to reproduce

```js
const http = require('http');
const https = require('https');
const got = require('got');

const agentOptions = {
  keepAlive: true, // <--- If you set this to false it will pass on Node 14.
  timeout: 30000,
};
const httpAgent = new http.Agent(agentOptions);
const httpsAgent = new https.Agent(agentOptions);

const cacheClient = got.extend({
    cache: {
        get: (key) => {
            return undefined;
        },
        set: (key, value) => {

        }
    }
});

const cacheAgentClient = cacheClient.extend({  
    timeout: 1000 * 4,
    agent: {
      http: httpAgent,
      https: httpsAgent,
    },
    http2: false,
});

const withAgentClient = got.extend({  
  timeout: 1000 * 4,
  agent: {
    http: httpAgent,
    https: httpsAgent,
  },
  http2: false,
});

(async () => {
    const options = {
      method: 'GET',
      throwHttpErrors: false,
    };

    const url = 'https://productcatalog.channeladvisor.com/token';

    const direct = await got(url, options);
    console.log('Without cache or agent', direct.statusCode);

    const withCache = await cacheClient(url, options);
    console.log('With cache', withCache.statusCode);

    const withAgent = await withAgentClient(url, options);
    console.log('With agent', withAgent.statusCode);

    const withCacheAndAgent = await cacheAgentClient(url, options);
    console.log('With cache and agent', withCacheAndAgent.statusCode);

    console.log('Done');
})();
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment] 2020-11-17 21:49
Duplicate of #1385

**Closed by szmarczak** 2020-11-17 21:49 UTC
