### ISSUE TITLE
Error when runing code from Testing section

### ISSUE THREAD

**Issue by norbornen** [sindresorhus/got#837] opened 2019-07-22 09:58 UTC
#### Describe the bug

 - Node.js version: v12.5.0
 - OS & version: macOS 10.14.5

I get an error when I run the code from the "[testing](https://github.com/sindresorhus/got#testing)" example.

```
GotError [RequestError]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type function
    at handleRequest (/Users/xxx/tmp/gottt/node_modules/got/source/request-as-event-emitter.js:214:15)
    at get (/Users/xxx/tmp/gottt/node_modules/got/source/request-as-event-emitter.js:234:5)
    at Immediate.<anonymous> (/Users/xxx/tmp/gottt/node_modules/got/source/request-as-event-emitter.js:305:10) {
  name: 'RequestError',
  code: 'ERR_INVALID_ARG_TYPE',
  host: 'sindresorhus.com:443',
  hostname: 'sindresorhus.com',
  method: 'GET',
  path: '/',
```

What's wrong with this code?

**Comment by szmarczak** [comment] 2019-07-22 21:16
1. Why haven't you filled out the template properly? You're missing two ticks.
2. Why didn't you search through closed issues?

Duplicate of #817

**Closed by szmarczak** 2019-07-22 21:16 UTC
