### ISSUE TITLE
Wrong TypeScript response type when using json responseType default

### ISSUE THREAD

**Issue by sunknudsen** [sindresorhus/got#1354] opened 2020-07-10 13:18 UTC
#### Describe the bug

 - Node.js version: 12.14.1
 - OS & version: macOS 10.15.5

#### Actual behavior

Type of `response` is string.

#### Expected behavior

Type of `response` is unknown.

#### Code to reproduce

```typescript
"use strict"

import got from "got"

const client = got.extend({
  responseType: "json",
})

;(async () => {
  let response = await client.get("search", { // Type of response is string, should be unknown right?
    searchParams: {
      email: "john@example.net",
    },
  })
})()
```

#### Checklist

- [ x ] I have read the documentation.
- [ x ] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment] 2020-07-10 14:36
Duplicate of #1117

**Closed by szmarczak** 2020-07-10 14:36 UTC
