### ISSUE TITLE
no stacktrace

### ISSUE THREAD

**Issue by joshxyzhimself** [sindresorhus/got#1736] opened 2021-06-01 09:19 UTC
#### Describe the bug

 - Node.js version: 16.2
 - OS & version: ubuntu 20.04

#### Actual behavior

It has no stacktrace, you know those that when you click takes you to the lines of code that led to that error

```
HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/home/user/Documents/project/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: undefined,
  timings: {
    start: 1622538853719,
    socket: 1622538853721,
    lookup: 1622538853792,
    connect: 1622538853824,
    secureConnect: 1622538853919,
    upload: 1622538853919,
    response: 1622538854137,
    end: 1622538854138,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 2,
      dns: 71,
      tcp: 32,
      tls: 95,
      request: 0,
      firstByte: 218,
      download: 1,
      total: 419
    }
  }
}
```

#### Expected behavior

It has stacktrace

#### Code to reproduce

```js
try {
  // any got request
} catch (e) {
  console.error(e);
  throw e;
}
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by joshxyzhimself** [comment] 2021-06-01 09:29
e.stack is just

```
HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/home/user/Documents/project/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

anyone know where the correct stacktrace is stored?

---

for illustration purposes, the following code correctly tells me that the source of the error was the `await` line at at line `3`.

```js
process.nextTick(async () => {
  try {
    await new Promise((resolve, reject) => setTimeout(() => reject(new Error('Test error.')), 1));
  } catch (e) {
    console.error(e);
  }
});
```

```
user@device:~/Documents/user$ node ./test.js
Error: Test error.
    at Timeout._onTimeout (/home/jxyz/Documents/user/test.js:3:68)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

is `got` intentionally eating those errors?

**Comment by joshxyzhimself** [comment] 2021-06-04 08:47
This is really hard to work with, good lord.

**Comment by szmarczak** [comment] 2021-06-05 21:18
> for illustration purposes, the following code correctly tells me that the source of the error was the await line at at line 3.

Node.js ate the trace where the promise was called as well. Same happens in Got, we can do nothing about it.

 The error is created in `dist/source/as-promise/index.js`, line 117.

---

In the `v11` branch:

```diff
diff --git a/source/core/index.ts b/source/core/index.ts
index 084d0a3..22a0d81 100644
--- a/source/core/index.ts
+++ b/source/core/index.ts
@@ -2159,6 +2159,7 @@ export default class Request extends Duplex implements RequestEvents<Request> {
                        this.push(null);
                });
 
+               console.log('core', new Error().stack);
                this.emit('response', response);
 
                for (const destination of this[kServerResponsesPiped]) {
```

```diff
diff --git a/source/as-promise/index.ts b/source/as-promise/index.ts
index efd9470..34d6f54 100644
--- a/source/as-promise/index.ts
+++ b/source/as-promise/index.ts
@@ -125,6 +125,7 @@ export default function asPromise<T>(normalizedOptions: NormalizedOptions): Canc
                                }
 
                                if (!isResponseOk(response)) {
+                                       console.log('promise', new Error().stack);
                                        request._beforeError(new HTTPError(response));
                                        return;
                                }
```


```
core Error
    at Request._onResponseBase (/home/szm/Desktop/got/dist/source/core/index.js:916:29)
    at Request._onResponse (/home/szm/Desktop/got/dist/source/core/index.js:935:24)
    at ClientRequest.<anonymous> (/home/szm/Desktop/got/dist/source/core/index.js:949:23)
    at Object.onceWrapper (node:events:485:26)
    at ClientRequest.emit (node:events:390:22)
    at ClientRequest.origin.emit (/home/szm/Desktop/got/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:636:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:129:17)
    at TLSSocket.socketOnData (node:_http_client:502:22)
    at TLSSocket.emit (node:events:378:20)
promise Error
    at Request.<anonymous> (/home/szm/Desktop/got/dist/source/as-promise/index.js:117:44)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

`core` is called right before emitting `response`, and `promise` is called when the `response` handler is executed.

**Comment by szmarczak** [comment] 2021-06-05 21:18
Duplicate of #1077

**Closed by szmarczak** 2021-06-05 21:18 UTC
