### ISSUE TITLE
GotRequest overloads don't obey resolveBodyOnly on instance

### ISSUE THREAD

**Issue by es50678** [sindresorhus/got#1822] opened 2021-08-06 02:37 UTC
#### Describe the bug
- got version: 11.8.2
 - Node.js version: v14.17.1
 - OS & version: macOS Big Sur 11.5
 - typescript version: 4.3.5
 - tsconfig:
 ```
{
  "compilerOptions": {
    "lib": ["es2017"],
    "module": "commonjs",
    "target": "es2017",

    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "declaration": true,
    "inlineSourceMap": true,
    "inlineSources": true
  }
}
```

When I create a `got` instance with `resolveBodyOnly` set to `true`, the type checker still things that the body is wrapped in a response.

#### Actual behavior
```js
void (async () => {
  const jsonBodyClient = got.extend({
    responseType: 'json',
    resolveBodyOnly: true,
  });

  interface ResType {
    foo: string;
    bar: string;
  }

  const test = await jsonBodyClient<ResType>('issue/details');
  test.foo;
  //  => TS2339: Property 'foo' does not exist on type 'Response '.
})();
```

#### Expected behavior
```js
void (async () => {
  const jsonBodyClient = got.extend({
    responseType: 'json',
    resolveBodyOnly: true,
  });

  interface ResType {
    foo: string;
    bar: string;
  }

  const test = await jsonBodyClient<ResType>('issue/details');
  test.foo; // should not throw typescript error
})();
```

#### Code to reproduce

```js
void (async () => {
  const jsonBodyClient = got.extend({
    responseType: 'json',
    resolveBodyOnly: true,
  });

  interface ResType {
    foo: string;
    bar: string;
  }

  const test = await jsonBodyClient<ResType>('issue/details');
  test.foo;
  //  => TS2339: Property 'foo' does not exist on type 'Response '.
})();
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment] 2021-08-06 05:53
Duplicate of #1117

**Closed by szmarczak** 2021-08-06 05:53 UTC
