### ISSUE TITLE
Got and typescript: why @types/got ?

### ISSUE THREAD

**Issue by nkint** [sindresorhus/got#825] opened 2019-06-27 09:02 UTC
#### What would you like to discuss?

tltr: Why do I need `@types/got` ?

Hi!
Got is written in typescript but installing it via `npm install` does not seems to get types:

```sh
➜  ~ cd /tmp
➜  /tmp mkdir got-test
➜  /tmp cd got-test
➜  got-test npm init
➜  got-test npm i --save got
➜  got-test find ./node_modules/got/
```

I get this result:

```
./node_modules/got/
./node_modules/got//license
./node_modules/got//source
./node_modules/got//source/as-stream.js
./node_modules/got//source/known-hook-events.js
./node_modules/got//source/merge.js
./node_modules/got//source/get-response.js
./node_modules/got//source/index.js
./node_modules/got//source/create.js
./node_modules/got//source/utils
./node_modules/got//source/utils/is-form-data.js
./node_modules/got//source/utils/timed-out.js
./node_modules/got//source/utils/deep-freeze.js
./node_modules/got//source/utils/get-body-size.js
./node_modules/got//source/utils/url-to-options.js
./node_modules/got//source/progress.js
./node_modules/got//source/errors.js
./node_modules/got//source/as-promise.js
./node_modules/got//source/normalize-arguments.js
./node_modules/got//source/request-as-event-emitter.js
./node_modules/got//readme.md
```

No `.d.ts` file in here, so vscode is not happy:

```
Could not find a declaration file for module 'got'. '/.../node_modules/got/source/index.js' implicitly has an 'any' type.
  Try `npm install @types/got` if it exists or add a new declaration (.d.ts) file containing `declare module 'got'; ts(7016)
```

Good but not super good (the project is written in typescript, should have types definition), let's go with
```sh
npm i --save @types/got
```

Now vscode is happy.

#### Versions:

- node 12.4.0
- npm 6.9.0
- tsc 3.5.2
- got 9.6.0
- @types/got@9.6.0

#### Checklist

- [x] I have read the documentation.
- [x] I have read the node_modules files.

**Comment by sindresorhus** [comment] 2019-06-27 10:06
Duplicate of #804

**Closed by sindresorhus** 2019-06-27 10:06 UTC

**Comment by sindresorhus** [comment] 2019-09-17 09:32
We have an alpha version of v10 out if you wanna help us test: https://github.com/sindresorhus/got/releases/tag/v10.0.0-alpha.1
