### ISSUE TITLE
Stack trace

### ISSUE THREAD

**Issue by polRk** [sindresorhus/got#1116] opened 2020-03-11 10:36 UTC
How do I see where an error occurred in MY code

```
    GotError: Timeout awaiting 'request' for 5000ms
        at onError (/Users/polrk/github.com/***/node_modules/got/dist/source/request-as-event-emitter.js:137:29)
        at ClientRequest.<anonymous> (/Users/polrk/github.com/***/node_modules/got/dist/source/request-as-event-emitter.js:157:17)
        at ClientRequest.emit (events.js:215:7)
        at ClientRequest.EventEmitter.emit (domain.js:476:20)
        at ClientRequest.origin.emit (/Users/polrk/github.com/***/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
        at Timeout.timeoutHandler [as _onTimeout] (/Users/polrk/github.com/***/node_modules/got/dist/source/utils/timed-out.js:40:17)
        at listOnTimeout (internal/timers.js:533:17)
        at Timeout.timeoutHandler [as _onTimeout] (/Users/polrk/github.com/***/node_modules/got/dist/source/utils/timed-out.js:40:31)
        at listOnTimeout (internal/timers.js:533:17)
        at processTimers (internal/timers.js:475:7)
```

**Comment by szmarczak** [comment] 2020-03-11 16:03
Duplicate of #1077

**Closed by szmarczak** 2020-03-11 16:03 UTC
