### ISSUE TITLE
got.stream not setting http headers

### ISSUE THREAD

**Issue by hazrul** [sindresorhus/got#481] opened 2018-04-25 15:19 UTC
const opt = {
    headers: {accept: 'text/plain','content-type': 'application/pdf'}
  }

got.stream.put(URL, opt).on('request', req => { console.log(req)});

the _headers for the req is not set

**Comment by sindresorhus** [comment] 2018-04-25 16:03
Can you submit a pull request with a [failing test](https://github.com/avajs/ava#failing-tests)? I'm requesting this as most issues like these are just users using the module incorrectly or an unrelated problem.

**Comment by rainder** [comment] 2018-05-29 12:35
I have the same problem I guess.

```js
const got = require('got');

const readStream = got.stream.get('http://domain.com/');
const writeStream = got.stream.post('http://domain.com/');

readStream.pipe(writeStream);
```

this code just crashes the entire app with the error

```
buffer.js:514
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type object
    at Function.byteLength (buffer.js:514:11)
    at Timeout.setInterval [as _onTimeout] (/private/tmp/got/node_modules/got/index.js:207:35)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)

```

`req._header` is set to null in this case, hence error is thrown in setTimeout callback function which crashes the app. Any ideas?

**Comment by rainder** [comment] 2018-05-29 14:17
the only way to make my example work is to wait for a response event be be emitted before creating writeStream.

```js
const got = require('got');

const readStream = got.stream.get('http://domain.com/');

readStream.once('response', () => {
  const writeStream = got.stream.post('http://domain.com/');
  readStream.pipe(writeStream);
});
```


also, same error occurs if you just create post stream without piping to it anything

```js
const got = require('got');

got.stream.post('http://domain.com/'); //throws TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type object

```

**Comment by szmarczak** [comment] 2018-07-09 08:05
Duplicate of #458

**Closed by szmarczak** 2018-07-09 08:05 UTC
