### ISSUE TITLE
Cannot find name 'URLSearchParams'

### ISSUE THREAD

**Issue by kirillgroshkov** [sindresorhus/got#960] opened 2019-12-03 18:19 UTC
#### What would you like to discuss?

I've just upgraded to `got@10` and got this TypeScript error:

```
tsc
node_modules/got/dist/source/utils/options-to-url.d.ts:12:71 - error TS2304: Cannot find name 'URLSearchParams'.
```

I figured it's because in my `tsconfig.json` `libs` I don't have `dom`. I'm consciously not using `dom` there to avoid importing/using Browser types that I never need in Node.js project (it caused me issues in the past, e.g global dom `Request` type clashes with Express.js `Request` type).

Is there a way to use `got@10` in a TypeScript project without `dom` in `libs`?

#### Checklist

- [x] I have read the documentation.

**Comment by sindresorhus** [comment] 2019-12-03 18:39
// @pmmmwh

**Comment by pmmmwh** [comment] 2019-12-03 18:45
I think I know what is causing this.

**Comment by pmmmwh** [comment] 2019-12-03 21:01
> #### What would you like to discuss?
> 
> I've just upgraded to `got@10` and got this TypeScript error:
> 
> ```
> tsc
> node_modules/got/dist/source/utils/options-to-url.d.ts:12:71 - error TS2304: Cannot find name 'URLSearchParams'.
> ```
> 
> I figured it's because in my `tsconfig.json` `libs` I don't have `dom`. I'm consciously not using `dom` there to avoid importing/using Browser types that I never need in Node.js project (it caused me issues in the past, e.g global dom `Request` type clashes with Express.js `Request` type).
> 
> Is there a way to use `got@10` in a TypeScript project without `dom` in `libs`?
> #### Checklist
> 
>     * [x]  I have read the documentation.

Is it possible to share some reproduce-able code? I already know the culprit, but my local setup miraculously still compiles.

@sindresorhus This is actually a regression of https://github.com/sindresorhus/got/issues/876#issuecomment-558813981. Apparently the issue is much deeper - because even though it would compile for Got's project, the augmented global types won't get populated to the users and thus TypeScript is doing its thing to try resolving the types. I guess we have to resort to moving `url.d.ts` into our types file so that it will get bundled, or resort to using the imported version from `url` until the types are properly fixed from DefinitelyTyped.

@szmarczak Thoughts?

**Comment by szmarczak** [comment] 2019-12-04 13:38
@pmmmwh It's because the `types` folder is not included in the `dist/source` folder:

<details>
<summary>Screenshot</summary>

![Screenshot](https://user-images.githubusercontent.com/36894700/70146927-87ad8e00-16a3-11ea-8b22-8329056113be.png)

</details>

**Comment by pmmmwh** [comment] 2019-12-04 15:02
> @pmmmwh It's because the `types` folder is not included in the `dist/source` folder:
> 
> Screenshot
> ![Screenshot](https://user-images.githubusercontent.com/36894700/70146927-87ad8e00-16a3-11ea-8b22-8329056113be.png)

Yes, because `tsc` won't output those non-module files.

**Comment by szmarczak** [comment] 2019-12-04 20:20
I don't think `tsc` allows exporting `*.d.ts` files yet...

**Comment by pmmmwh** [comment] 2019-12-04 20:50
> I don't think `tsc` allows exporting `*.d.ts` files yet...

We would have to either:
1. Manually copy those files into our export, or,
2. Move declaration override code into one of the modules.

Which one do you prefer?

**Comment by sindresorhus** [comment] 2019-12-04 21:23
Let’s go with 2.

**Comment by szmarczak** [comment] 2019-12-05 21:27
`index.ts` perhaps?

**Comment by sindresorhus** [comment] 2019-12-06 04:11
Sure. It’s just a temporary workaround. Doesn’t matter where it lives. We just need to fix it ASAP.

**Comment by pmmmwh** [comment] 2019-12-06 09:41
> Sure. It’s just a temporary workaround. Doesn’t matter where it lives. We just need to fix it ASAP.

I can push when I'm home (5 hours from now).

**Closed** 2019-12-07 17:15 UTC
Labels: types, ✭ help wanted ✭

**Comment by normano** [comment] 2019-12-08 23:03
I guess the fix here broke it or am I missing some typescript option?

node_modules/got/dist/source/utils/types.d.ts:182:11 - error TS2300: Duplicate identifier 'URL'.

182     class URL {
              ~~~

  node_modules/typescript/lib/lib.dom.d.ts:16052:11
    16052 interface URL {
                    ~~~
    'URL' was also declared here.
  node_modules/typescript/lib/lib.dom.d.ts:16068:13
    16068 declare var URL: {
                      ~~~
    and here.

node_modules/got/dist/source/utils/types.d.ts:199:11 - error TS2300: Duplicate identifier 'URLSearchParams'.

199     class URLSearchParams implements Iterable<[string, string]> {
              ~~~~~~~~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:16078:11
    16078 interface URLSearchParams {
                    ~~~~~~~~~~~~~~~
    'URLSearchParams' was also declared here.
  node_modules/typescript/lib/lib.dom.d.ts:16107:13
    16107 declare var URLSearchParams: {
                      ~~~~~~~~~~~~~~~
    and here.
  node_modules/typescript/lib/lib.dom.iterable.d.ts:263:11
    263 interface URLSearchParams {
                  ~~~~~~~~~~~~~~~
    and here.

node_modules/typescript/lib/lib.dom.d.ts:16052:11 - error TS2300: Duplicate identifier 'URL'.

16052 interface URL {
                ~~~

  node_modules/got/dist/source/utils/types.d.ts:182:11
    182     class URL {
                  ~~~
    'URL' was also declared here.

node_modules/typescript/lib/lib.dom.d.ts:16068:13 - error TS2300: Duplicate identifier 'URL'.

16068 declare var URL: {
                  ~~~

  node_modules/got/dist/source/utils/types.d.ts:182:11
    182     class URL {
                  ~~~
    'URL' was also declared here.

node_modules/typescript/lib/lib.dom.d.ts:16078:11 - error TS2300: Duplicate identifier 'URLSearchParams'.

16078 interface URLSearchParams {
                ~~~~~~~~~~~~~~~

  node_modules/got/dist/source/utils/types.d.ts:199:11
    199     class URLSearchParams implements Iterable<[string, string]> {
                  ~~~~~~~~~~~~~~~
    'URLSearchParams' was also declared here.

node_modules/typescript/lib/lib.dom.d.ts:16107:13 - error TS2300: Duplicate identifier 'URLSearchParams'.

16107 declare var URLSearchParams: {
                  ~~~~~~~~~~~~~~~

  node_modules/got/dist/source/utils/types.d.ts:199:11
    199     class URLSearchParams implements Iterable<[string, string]> {
                  ~~~~~~~~~~~~~~~
    'URLSearchParams' was also declared here.

node_modules/typescript/lib/lib.dom.iterable.d.ts:263:11 - error TS2300: Duplicate identifier 'URLSearchParams'.

263 interface URLSearchParams {
              ~~~~~~~~~~~~~~~

  node_modules/got/dist/source/utils/types.d.ts:199:11
    199     class URLSearchParams implements Iterable<[string, string]> {
                  ~~~~~~~~~~~~~~~
    'URLSearchParams' was also declared here.

**Comment by szmarczak** [comment] 2019-12-08 23:16
@normano

1. You can use code blocks

```
like this
```

2. What TS version are you using?

**Comment by normano** [comment] 2019-12-08 23:32
Typescript 3.7.2

**Comment by kirillgroshkov** [comment] 2019-12-09 09:02
FYI: for my project it was fixed (thanks!). But I'm not using `lib: "dom"` there

**Comment by normano** [comment] 2019-12-09 09:20
There is no reference to "dom" in my tsconfig or anywhere as far as find can find.
