### ISSUE TITLE
electron not included as dependency 

### ISSUE THREAD

**Issue by alanzhaonys** [sindresorhus/got#373] opened 2017-09-14 00:13 UTC
got uses electron package but why it's not included as dependency in package.json?

**Comment by sindresorhus** [comment] 2017-09-14 02:11
Duplicate of #345.

Got only uses Electron when in an Electron environment where the `electron` dependency is injected for you.

**Comment by sindresorhus** [comment] 2017-09-14 02:11
Got only uses Electron when in an Electron environment where the `electron` dependency is injected for you.

**Closed by sindresorhus** 2017-09-14 02:11 UTC
