### ISSUE TITLE
GotError.toJSON()

### ISSUE THREAD

**Issue by mfulton26** [sindresorhus/got#1136] opened 2020-03-27 13:04 UTC
#### What problem are you trying to solve?

Easier serialization of errors for logging purposes.

#### Describe the feature

`axios` recently implemented [`toJSON()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON_behavior) on `AxiosError` (https://github.com/axios/axios/pull/1625).

This is super handy when logging errors as `AxiosError` gets stringified in JSON loggers (e.g. `bunyan`) to a very sensible subset of all that the error and the request/response include.

##### Example `JSON.stringify(axiosError)`:

```json
{
  "message": "Request failed with status code 404",
  "name": "Error",
  "stack": "Error: Request failed with status code 404\n    at createError…",
  "config": {
    "url": "https://www.google.com/foo",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "User-Agent": "axios/0.19.2"
    },
    "transformRequest": [null],
    "transformResponse": [null],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "method": "get"
  }
}
```

##### Example `JSON.stringify(gotError)`:

```json
{ "name": "HTTPError" }
```

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by szmarczak** [comment] 2020-03-27 13:21
> Easier serialization of errors for logging purposes.

What information do you expect to serialize? The `options` property is not enumerable **on purpose** to prevent leaking tokens etc.

**Comment by szmarczak** [comment] 2020-03-27 13:23
Possible duplicate of #559

**Comment by szmarczak** [comment] 2020-04-01 15:12
I think it'd be best to override `.toJSON` via a `beforeError` hook.

**Closed by szmarczak** 2020-04-01 15:12 UTC
Labels: question

**Comment by szmarczak** [comment] 2020-04-01 16:28
Duplicate of #1067
