### ISSUE TITLE
Slow http2 requests for http3 pages?

### ISSUE THREAD

**Issue by Allain55** [sindresorhus/got#1722] opened 2021-05-20 10:41 UTC
#### What would you like to discuss?
Not sure if this is a got bug but I got curious. I run some small tests against http3 pages using Cloudflare. I usually see http2 requests are 20-30%, sometimes even 50% slower than requests for http pages. These are not realiable enough tests.

For example this page us using Cloudflare's HTML cache and using http3:
https://footballbreak.com/404/

I tested got for http and http2 pages but haven't seen this negative effect
I tested with https://mirror.leaseweb.com/speedtest/100mb.bin and using http2 was faster
I used Node 16.2 and got 11.8.2

Could someone run reliable tests to verify my hypothesis?

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment] 2021-05-20 15:51
Got doesn't support HTTP/3.

**Comment by szmarczak** [comment] 2021-05-20 15:51
If you're seeing slow downloads, it may be caused by https://github.com/nodejs/node/issues/38426

**Comment by Allain55** [comment] 2021-05-21 08:32
Yeah I know that Got doesn't support HTTP/3 I was just execting at least the same performance using http2 for http3 pages.
Could you point me to the right direction where could I increase the window size for http2 requests? I couldn't find anything about this in the docs neither in Got. I'd try to increase it and see what happens. 
Thank you!

**Comment by szmarczak** [comment] 2021-05-21 16:35
The issue is fixed in the `main` branch. But you're right, we also need to mention this in the docs.

**Closed** 2021-07-13 22:57 UTC
Labels: documentation
