### ISSUE TITLE
Simultaneous use of option json with body as FormData

### ISSUE THREAD

**Issue by tolec** [sindresorhus/got#600] opened 2018-09-03 15:59 UTC
Seems that `json` option is responsible simultaneously for sending and parsing.

When `json` is set to true, the response will be parsed as json. Ok. However, in case if I want to send FormData and at the same time I want to receive response data as json, it will fail [here](https://github.com/sindresorhus/got/blob/5f191b90e189acb8e2f721d676775ab667532251/source/normalize-arguments.js#L141) – because it checks that if I enable `json` option then it requires the `body` option to be an Object or Array.

**Comment by szmarczak** [comment] 2018-09-03 16:03
Duplicate of #511 #383 #318 #467

**Closed by szmarczak** 2018-09-03 16:03 UTC
Labels: duplicate

**Comment by tolec** [comment] 2018-09-03 16:29
So, as I understood from https://github.com/sindresorhus/got/issues/383, the only way now to use both `FormData` and `json` option is to parse response myself, right?

**Comment by szmarczak** [comment] 2018-09-03 16:59
Yup.
