### ISSUE TITLE
Requests hangs with cacheable-request and keepalive agent on Node 14 for some URLs

### ISSUE THREAD

**Issue by adityapatadia** [sindresorhus/got#1522] opened 2020-11-11 11:29 UTC
#### Describe the bug

 - Node.js version: 14.15
 - OS & version: Macos 10.15

#### Actual behavior

Got never responds and gets stuck somewhere. Program execution never moves ahead.

#### Expected behavior

Got should fire proper response

#### Code to reproduce

```js
const got = require("got"),
  http = require("http"),
  https = require("https");

const agent = {
  http: new http.Agent({ keepAlive: true }),
  https: new https.Agent({ keepAlive: true })
};

var requestOptions = {
  timeout: 35000, // milliseconds
  responseType: 'buffer',
  retry: 0,
  maxRedirects: 5,
  dnsCache: false,
  shared: false,
  // this code works if below argument is commented.
  agent,
  cache: new Map()
};

(async () => {
  const response = await got.get("https://www.lttc.ntu.edu.tw/eju.htm?fill=solid&v=8", requestOptions);
  // below line line never gets printed....
  console.log("response received");
})();

```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by adityapatadia** [comment] 2020-11-11 11:42
I should also mention this happens only with Node 14 and everything works fine under Node 12.

**Comment by szmarczak** [comment] 2020-11-11 12:57
What about Node.js 15?

**Comment by adityapatadia** [comment] 2020-11-11 13:45
Does not work on 15.

**Comment by szmarczak** [comment] 2020-11-11 21:28
Hmm... Works on `v13.14.0`... Investigating.

**Comment by szmarczak** [comment] 2020-11-11 21:44
After some investigation I have come to a conclusion that this is a duplicate of #1385 (I first wasn't initially really sure how to reproduce the issue, so thanks for this report!)

**Closed by szmarczak** 2020-11-11 21:44 UTC
Labels: bug, ✭ help wanted ✭

**Comment by szmarczak** [comment] 2020-11-11 22:00
https://github.com/sindresorhus/got/issues/1385#issuecomment-725685047
