### ISSUE TITLE
download Excel File with GOT

### ISSUE THREAD

**Issue by osmenia** [sindresorhus/got#1160] opened 2020-04-17 22:21 UTC
"got": "^10.7.0"

I would like to download Excel File with GOT.

```
const downloadUrl ="https://file-examples.com/wp-content/uploads/2017/02/file_example_XLS_10.xls"
CookieArray = "CookieArray test";

async function downloadFileGot(downloadUrl, CookieArray) {
  try {
    const config = {
      url: downloadUrl,
      method: "GET",
      headers: {
        Accept:
          "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
        "Accept-Encoding": "gzip, deflate, br",
        "Accept-Language":
          "en-US,en;q=0.9,fr;q=0.8,ro;q=0.7,ru;q=0.6,la;q=0.5,pt;q=0.4,de;q=0.3",
        "Cache-Control": "max-age=0",
        Connection: "keep-alive",
        "Upgrade-Insecure-Requests": "1",
        "User-Agent":
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36",
        Cookie: CookieArray,
      },
      responseType: "arraybuffer",
    };

    return await got(config);

  } catch (error) {
    console.log(`Something happened: ${error}`);
  }
}
```

I am getting error:
Something happened: RequestError: connect ECONNREFUSED 127.0.0.1:443
undefined

What i am doing wrong? 

thanks for your help.

**Comment by szmarczak** [comment] 2020-04-17 22:28
1. Is there a reason you didn't fill in the issue template?
2. What Got version are you using?

**Comment by osmenia** [comment] 2020-04-17 22:37
Sorry,

where can i find  issue template?

GOT Version: "got": "10.7.0"

thanks

**Comment by szmarczak** [comment] 2020-04-18 08:52
> where can i find issue template?

It's automatically set up when you open a new issue template.

> GOT Version: "got": "10.7.0"

Possible duplicate of #1039

**Comment by szmarczak** [comment] 2020-04-20 18:50
Tested on Got 11.0.1, no such issue happens.

**Closed by szmarczak** 2020-04-20 18:50 UTC
