### ISSUE TITLE
No retry on timeout in v7

### ISSUE THREAD

**Issue by MartinKolarik** [sindresorhus/got#357] opened 2017-08-12 20:11 UTC
When a `timeout` option is set, got@7 doesn't make any retry on timeout. got@6 respects the `retries` option in this case. Looks like a bug in the latest version?

**Comment by sindresorhus** [comment] 2017-08-12 21:37
Duplicate of https://github.com/sindresorhus/got/issues/344

**Closed by sindresorhus** 2017-08-12 21:37 UTC

**Comment by elpaxdota** [comment] 2017-10-04 14:35
Sorry for opening this but I need some explanation. I have this code:

	var req = got(url, { retries: 10, timeout: 3000 })
	.then(response => {
		return response.body;
	})
	.catch(err => {
		if (err.name === "RequestError" && err.code === "ETIMEDOUT") {
			console.log("get request timed out");
			req.cancel();
		}
	});
	return req;

So timeout is working, but req does not repeat. What I need to do ? I have got@7.0.1 installed.
