### ISSUE TITLE
How to get error response body in beforeRetry hook ?

### ISSUE THREAD

**Issue by geminigeek** [sindresorhus/got#1423] opened 2020-08-26 20:23 UTC
How to get error response body in beforeRetry hook ?

i am getting error.response.statusCode fine but not getting error.response.body ?

I have read the documentation. no mention of how to get error body ?

sample code to generate the issue 

```js
const got = require("got")

got(errorUrl, {
  hooks: {
    beforeRetry: [
      (options, error, retryCount) => {
       console.log(error.response.statusCode) //408 
        console.log(error.response.body) // undefined  [issue]  Expected : this is 408 error body
      },
    ],
  },
})
```

the php code i used to generate error is below errorUrl. 

`<?php 
header('HTTP/1.1 408');
echo  'this is 408 error body';
?>
`

**Comment by szmarczak** [comment] 2020-08-26 23:11
Reproducible:

```js
const got = require("got");
const server = require('http').createServer((request, response) => {
    response.statusCode = 500;
    response.end('nope');
});

server.listen(() => {
   got(`http://localhost:${server.address().port}`, {
      hooks: {
        beforeRetry: [
          (options, error, retryCount) => {
           console.log(error.response.statusCode) //408 
            console.log(error.response.body) // undefined  [issue]  Expected : this is 408 error body
          },
        ],
      },
    }).catch(() => {}); 
});
```

**Comment by Nilithus** [comment] 2020-08-27 21:47
Is this happening with a specific version of Node or the Library?

When I cloned down `got` added the reproducible code into a `test.js` file and ran it I got `nope` back for `error.response.body`

![Screen Shot 2020-08-27 at 5 45 39 PM](https://user-images.githubusercontent.com/1783861/91498120-38d90180-e88d-11ea-9821-5a1dff7bec23.png)

**Comment by geminigeek** [comment] 2020-08-27 21:51
hi,
my version is same  "got": "11.5.2",  node v12.10.0,  os windows 10 64 bit

i am not getting body?

**Comment by Giotino** [comment] 2020-08-31 15:46
It seems to be fixed in the master branch since commit https://github.com/sindresorhus/got/commit/707219825b2f8ff3df597230a53244636df21642

**Comment by szmarczak** [comment] 2020-08-31 20:09
Ah yes, the `_beforeError` is removed for Promise API and therefore it defines the body here:

https://github.com/sindresorhus/got/blob/b134aa488a3d903d9571914b0f8b267340b767a9/source/core/index.ts#L2481

**Closed by szmarczak** 2020-08-31 20:09 UTC
Labels: bug, regression, ✭ help wanted ✭
