### ISSUE TITLE
Change cacheable-request library to custom one

### ISSUE THREAD

**Issue by adityapatadia** [sindresorhus/got#948] opened 2019-11-28 15:20 UTC
#### What would you like to discuss?
Is there a way to change the cacheable-request library? If yes, let's document it. If it's not available, can we create some way to allow it?
...

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment] 2019-11-28 16:41
Duplicate of #875

**Closed by szmarczak** 2019-11-28 16:41 UTC
