### ISSUE TITLE
Incorrect Type on response body when got.extend is used with responseType

### ISSUE THREAD

**Issue by nediamond** [sindresorhus/got#1436] opened 2020-09-03 16:41 UTC
#### Describe the bug

 - Node.js version: 14.9.0 & 12.6.3
 - OS & version: Catalina 10.15.6 

#### Actual behavior
```js
const api = got.extend({responseType: 'json'});
const res = await api.get('https://myapi.com');
res.body # has type string
```
#### Expected behavior
```js
const api = got.extend({responseType: 'json'});
const res = await api.get('https://myapi.com');
res.body # has type unknown
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment] 2020-09-03 21:28
Duplicate of #1117

**Closed by szmarczak** 2020-09-03 21:28 UTC
