### ISSUE TITLE
decodeURIComponent basic auth

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/got#1249] opened 2020-05-11 20:20 UTC
#### Describe the bug

- Got version: `11.1.3`
 - Node.js version: `12.16.3` and `14.2.0`
 - OS & version: `macOS 10.15.4`

Similar to #1234, basic auth values are not decoded before sending to `http.request`, resulting in authentication failure.

#### Code to reproduce
These send "%3Duser" and "%3Dpass" to `http.request`:
```js
const url = new URL('http://host');
url.username = '=user';
url.password = '=pass';
got(new URL(url));
```
```js
got({
  password: '=user',
  url: 'http://host',
  username: '=user'
});
```
```js
const url = new URL('http://host');
got(`${url.protocol}//=user:=pass@${url.host}`);
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment] 2020-05-11 21:42
Duplicate of #1169

**Closed by szmarczak** 2020-05-11 21:42 UTC
