### ISSUE TITLE
11.6.1 hangs when running on node v14.10.0

### ISSUE THREAD

**Issue by benjamincburns** [sindresorhus/got#1441] opened 2020-09-09 00:05 UTC
#### Describe the bug

 - Node.js version: v14.10.0
 - OS & version: all

I use `got` in a node CLI tool. I accidentally published it with a `package-lock.json` instead of `npm-shrinkwrap.json`. Unfortunately this meant that my tool was tracking the latest version of `got`. When `got@11.6.1` was released, my tool started hanging when making HTTP requests when running under node v14.10.0.

I also see that [the CI build for `got`](https://github.com/sindresorhus/got/runs/1088472472) is broken for the v11.6.1 release commit. The failure occurred on the node v14 build, and apparently [the build failed due to tests timing out](https://travis-ci.com/github/sindresorhus/got/jobs/382443656#L869), which suggests that this issue is already reproduced extensively by the existing test suite.

#### Actual behavior

`got` hangs indefinitely when executing [this statement](https://github.com/PegaSysEng/quorum-dev-quickstart/blob/2e443b18c4a90c6f617712c1b6cce5c1ffdf62b5/src/service/orchestrate/index.ts#L91-L93)

#### Expected behavior

The line lined above would execute as normal.

#### Code to reproduce

See link above, or, per your CI (also linked above), just run your test suite under node v14.10.0

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by benjamincburns** [comment] 2020-09-09 02:57
I did a bit of testing, and it appears that this is only an issue on node v14.10.0, which was also released earlier today. I've done no digging to identify the actual bug, but given the version-specific nature of the beast, I would imagine that this is a bug in NodeJS, as a minor release has changed behaviour in existing code.

**Comment by targos** [comment] 2020-09-09 06:35
Reproduction:

```js
require('got')('https://www.google.com').then(console.log, console.log)
```

This logs the response in Node.js 14.9.0 and exits without any logs in Node.js 14.10.0

**Comment by Giotino** [comment] 2020-09-09 08:57
Following the discussion on https://github.com/nodejs/node/issues/35116

`this[kStopReading]` should be an indicator of "stop reading the stream" (as pointed out by @targos Node.JS v14.10.0 destroys the stream even on success, which is correct), but in the `_isAboutToError` getter is used as an indicator of an error state.

**Comment by ronag** [comment] 2020-09-09 11:00
Could somebody apply the following [PR](https://github.com/nodejs/node/pull/35120) on v14.x-staging, build it and try to reproduce this issue? To see if it resolves it.

**Comment by Giotino** [comment] 2020-09-09 12:51
@ronag I see no difference.
Neither with this
```js
require('got')('https://www.google.com').then(console.log, console.log)
```
Nor with the got tests.

**Comment by ronag** [comment] 2020-09-09 14:24
This is probably a problem with Node destroying the stream even though `autoDestroy: false`. https://github.com/nodejs/node/pull/35122

I would in general recommend that `destroy()` after `'end'` has been emitted should not be an error. Would also recommend `autoDestroy: true` in order to behave as normal streams.

**Comment by szmarczak** [comment] 2020-09-09 17:58
https://github.com/nodejs/node/issues/35116#issuecomment-689723287

**Comment by umaar** [comment] 2020-09-10 17:53
Heads up on v14.10.0 `got` wasn't working for me with [this code](https://github.com/umaar/wiki-globe/blob/1bbd8f93d87e727de274dea6fb0d9c16b3e089ee/index.js#L37-L39), ended up completely blowing through my API quota!

**Comment by wibobm** [comment] 2020-09-10 19:36
Noticed same hang when updating to node 14.10.  The most recent version of GOT that appears to works with node 14.10 is v11.5.2.

**Comment by richardlau** [comment] 2020-09-10 20:03
Node.js 14.10.1 was released today which reverted a commit that was introduced in 14.10.0 and should make things work again. There's ongoing work both in got and in Node.js to fix things for the next major version of Node.js (15).

**Comment by benjamincburns** [comment] 2020-09-11 06:00
@umaar I'm not a contributor to this project, so take this with a grain of salt, but my understanding is that got is tested against the latest release. You'll see there's a link to a failing CI build in my original description of the bug. I think what happened in this case was the timing of the node 4.10.0 release was so close to the timing of the got 11.6.1 release that the failure wasn't observed in the pre-release test run, but instead it became visible when building the tag after the release had been published.

There isn't really a great way to solve for this. The publish process could get tightened up a bit, but that doesn't solve for the hypothetical case where node 14.10.0 would've been released just after got's tag built successfully. In that scenario we still would've run into this problem, though with less direct evidence of the problem's existence. In practice this is a rather rare sort of bug to crop up, and the timing coinciding this closely makes it an especially rare/unlikely event, so the effort involved in tightening up got's release process likely wouldn't provide any measurable additional quality assurance.

**Comment by benjamincburns** [comment] 2020-09-11 06:10
Another lower cost mitigation might be to add automation that automatically [unpublishes](https://docs.npmjs.com/cli/unpublish) the release when building the tag fails, however this only works if CI is set up with NPM credentials. This likely isn't possible if 2FA is required for NPM writes to the got module.

**Comment by szmarczak** [comment] 2020-11-20 14:37
Closing since it's fixed on Node.js' side.

If you have any other ideas / comments, please share them at #1535 instead.

**Closed by szmarczak** 2020-11-20 14:37 UTC
Labels: bug, external
