### ISSUE TITLE
`beforeError` hook does not seem to work with `got.HTTPError`

### ISSUE THREAD

**Issue by pgaubatz** [sindresorhus/got#831] opened 2019-07-12 08:01 UTC
#### Describe the bug

 - Node.js version: v10.15.1
 - OS & version: Debian GNU/Linux 9.9 (stretch)

The `beforeError` hook does not trigger when an `got.HTTPError` is thrown.

#### Actual behavior

Given the code example below, the script does not output anything at all.

#### Expected behavior

However, the script is (at least that's what I'd expect) should output `beforeError hook called`.

#### Code to reproduce

```js
const assert = require('assert')
const http = require('http')
const got = require('got')

async function main() {
  const server = http.createServer((_, res) => {
    res.statusCode = 500
    res.end()
  })
  const client = got.extend({
    throwHttpErrors: true,
    hooks: {
      beforeError: [
        () => console.log('beforeError hook called')
      ]
    }
  })
  const port = 8888
  try {
    server.listen(port)
    await client(`http://localhost:${port}`)
  } catch (err) {
    assert.equal(err.name, 'HTTPError', 'an HTTPError is thrown')
  } finally {
    server.close()
  }
}

main().catch(console.error)
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment] 2019-07-12 09:56
Duplicate of #781

**Closed by szmarczak** 2019-07-12 09:56 UTC
