### ISSUE TITLE
Requests are resolved with empty body

### ISSUE THREAD

**Issue by arcanis** [sindresorhus/got#1496] opened 2020-10-10 21:02 UTC
#### Describe the bug

 - Node.js version: 14.0
 - OS & version: OSX

Ref: https://github.com/sindresorhus/got/pull/1256#issuecomment-706609515

Got on Node 14.0.0 returns empty bodies for all requests. After double-checking (I already did but messed the Node upgrade), **it seems to work on 14.13**. Still, it's an annoying behaviour for a minor release since it would make upgrading `got` in Yarn a BC-breaking change 🙁

#### Code to reproduce

The default one is enough:

```js
const got = require('got');

(async () => {
	try {
		const response = await got('https://sindresorhus.com');
		console.log(response.body);
		//=> '<!doctype html> ...'
	} catch (error) {
		console.log(error.response.body);
		//=> 'Internal server error ...'
	}
})();
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by arcanis** [comment] 2020-10-10 21:05
Seems like both 14.0 and 14.1 are affected; starting from 14.2 the bug disappears

**Comment by szmarczak** [comment] 2020-10-10 21:57
Duplicate of #1395 #1349 #1172

**Closed by szmarczak** 2020-10-10 21:57 UTC

**Comment by Michelle99798** [comment] 2020-10-10 22:09
Thanks
