### ISSUE TITLE
Node.JS 12 uncaught exception on TLS error

### ISSUE THREAD

**Issue by Giotino** [sindresorhus/got#1455] opened 2020-09-10 13:38 UTC
#### Describe the bug

 - Node.js version: 12 (tested on v12.18.3, latest available as of today)
 - OS & version: irrelevant

#### Actual behavior

Node.JS behavior: on some kind of errors (in this example `ERR_SSL_NO_PROTOCOLS_AVAILABLE`) the 'error' event on a https request (due to the TLS socket) is fired 2 times, the first is `ERR_SOCKET_CLOSED` the second one is `ERR_SSL_NO_PROTOCOLS_AVAILABLE`. The correct one should be the latter, while the first error code makes sense, it's too generic.

#### Expected behavior

Only `ERR_SSL_NO_PROTOCOLS_AVAILABLE` should be emitted.

#### How does this apply to Got?

Got only listen for the first 'error' event, for some reason I've not yet investigated it ignore `ERR_SOCKET_CLOSED`. `ERR_SSL_NO_PROTOCOLS_AVAILABLE` end up as a uncaught exception.

#### Code to reproduce

Below 2 examples one with "pure" Node.JS and the other with Got.
After the two examples a simple server example can be found.

Node.JS client
```js
const https = require('https');

const req = https.request('https://127.0.0.1:9999', {
  maxVersion: 'TLSv1.1',
});

req.on('error', (e) => {
  console.error(e);
});

req.end();
```

Got client
```js
const got = require('got');

const request = got.stream('https://127.0.0.1:9999', {
  maxVersion: 'TLSv1.1',
});

request.on('error', (error) => {
  console.log(error);
});
```

Server
```js
const https = require('https');

const server = https.createServer({
  minVersion: 'TLSv1.2',
});

server.listen(9999);
```

**Comment by szmarczak** [comment] 2020-09-10 13:58
I cannot reproduce on RunKit: https://runkit.com/szmarczak/5f5a30d0c15745001ab1ee69

**Comment by szmarczak** [comment] 2020-09-10 13:59
You may want to file an issue at https://github.com/nodejs/node/issues/new?template=1-bug-report.md

**Comment by Giotino** [comment] 2020-09-10 14:20
https://github.com/nodejs/node/issues/35142

**Comment by szmarczak** [comment] 2020-09-18 20:45
I thought this could be fixed on Got side by forcing `request.destroy()` but nope :(

**Comment by szmarczak** [comment] 2021-07-31 20:10
Closing as we don't support Node.js 12 anymore.

**Closed by szmarczak** 2021-07-31 20:10 UTC
Labels: bug, external, nodejs bug
