### ISSUE TITLE
NodeJS Crashes

### ISSUE THREAD

**Issue by vmalawade** [sindresorhus/got#2131] opened 2022-09-04 23:13 UTC
#### Describe the bug

 - Node.js version: 16 LTS
 - OS & version: Ubuntu 22 LTS

NodeJS Crashes with error

Error: The `onCancel` handler was attached after the promise settled.
    at onCancel (/home/tladmin/vaibhav/playoutv3/node_modules/p-cancelable/index.js:48:12)
    at makeRequest (/home/tladmin/vaibhav/playoutv3/node_modules/got/dist/source/as-promise/index.js:38:13)
    at Request.<anonymous> (/home/tladmin/vaibhav/playoutv3/node_modules/got/dist/source/as-promise/index.js:143:17)
    at Object.onceWrapper (node:events:628:26)
    at Request.emit (node:events:513:28)
    at Timeout.retry (/home/tladmin/vaibhav/playoutv3/node_modules/got/dist/source/core/index.js:1278:30)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

#### Actual behavior
I am not setting any retry - It is just doing simple get
...

#### Expected behavior
Should not crash.
Request is try/catch block.
...

#### Code to reproduce

```js
...
```

#### Checklist

- [ ] I have read the documentation.
- [ ] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment] 2022-10-09 12:53
Duplicate of https://github.com/sindresorhus/got/issues/1489

**Closed by szmarczak** 2022-10-09 12:53 UTC
