### ISSUE TITLE
Malformed response causing odd failure with no error

### ISSUE THREAD

**Issue by kjs3** [sindresorhus/got#1527] opened 2020-11-17 19:32 UTC
#### Describe the bug

 - Node.js version: 14.12.0 & 15.2.1
 - OS & version: MacOS Catalina (10.15.7) & Manjaro (rolling release, up to date)

I stumbled on a silent failure when parsing a bunch of podcast feeds. Specifically [this one](https://read.audioarchitect.co/feed/podcast).

Chrome fails with a `net::ERR_CONTENT_DECODING_FAILED` error.
Curl and the Axios lib seem to handle the response just fine.

#### Actual behavior
Silent failure. The promise doesn't seem to resolve at all. I'm not sure what's going on within the Node loop.

#### Expected behavior

A `ResponseError` is probably the right behavior. The fact that some other libs can handle this confuses the issue though.

#### Code to reproduce

```javascript
// got-test.js
const got = require('got')

main()

async function main() {
  const url = 'https://read.audioarchitect.co/feed/podcast'

  try {
    console.log('getting: ', url)
    const res = await got(url)
    console.log('never here: ', res)
  } catch (err) {
    console.error(err)
    console.log('never here either')
  }
}
```

```shell
node got-test.js
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by Giotino** [comment] 2020-11-17 21:01
The problem with that website is that it answer with the header `Content-Encoding: gzip` but the body is `plain`, so the decompress fails.

This issue is probably caused by https://github.com/sindresorhus/decompress-response

**Comment by szmarczak** [comment] 2020-11-17 21:51
Good catch!

**Comment by szmarczak** [comment] 2021-04-13 20:53
This is caused by https://github.com/nodejs/node/issues/34350 - unfortunately Node.js has marked this as `wontfix`, so we have to make a workaround for this...

**Comment by szmarczak** [comment] 2021-04-13 20:55
Duplicate of #1357 - need to check if it's still in the tests

**Comment by szmarczak** [comment] 2021-04-13 20:57
Yes, we still have this in the tests. Looks like this is a different variation but the error is `ParseError` as well.

**Comment by szmarczak** [comment] 2021-04-13 21:09
```
curl https://read.audioarchitect.co/feed/podcast -H 'accept-encoding: gzip, deflate, brotli' -v --http1.1 --ignore-content-length
```

**Closed** 2021-04-13 21:13 UTC
Labels: bug, external, nodejs bug

**Comment by szmarczak** [comment] 2021-04-13 21:14
@sindresorhus I'm really looking forward to `undici`. The native Node.js parser is giving me headaches.
