### ISSUE TITLE
Can’t use type with responseType option

### ISSUE THREAD

**Issue by sunknudsen** [sindresorhus/got#1122] opened 2020-03-16 13:18 UTC
#### Describe the bug

 - Node.js version: v12.14.1
 - OS & version: macOS Mojave 10.14.6

#### Actual behavior

I believe this issue is a TypeScript type declaration bug.

I am building on top of got and having issues with the `responseType` option.

#### Expected behavior

The following code block should not throw type error.

#### Code to reproduce

```typescript
import got from "got"

export type ResponseType = "text" | "json" | "buffer"

const send = async function(responseType: ResponseType) {
  console.log(await got({
    url: "https://api.example.net",
    method: "GET",
    responseType: responseType
  }))
}
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment] 2020-03-16 14:00
What is the type error?

**Comment by sunknudsen** [comment] 2020-03-16 14:01
@sindresorhus 

```shell
The last overload gave the following error.
  Argument of type '{ method: Method; url: string; searchParams: string; json: { [key: string]: any; }; headers: Headers; responseType: ResponseType; hooks: { beforeRequest: (() => Promise<void>)[]; beforeRetry: ((options: NormalizedOptions, error: GeneralError, retryCount: number) => Promise<...>)[]; }; }' is not assignable to parameter of type 'string | Merge<Merge<RequestOptions, Merge<GotOptions, URLOptions>>, { isStream: true; }>'.
    Type '{ method: Method; url: string; searchParams: string; json: { [key: string]: any; }; headers: Headers; responseType: ResponseType; hooks: { beforeRequest: (() => Promise<void>)[]; beforeRetry: ((options: NormalizedOptions, error: GeneralError, retryCount: number) => Promise<...>)[]; }; }' is not assignable to type 'Merge<Merge<RequestOptions, Merge<GotOptions, URLOptions>>, { isStream: true; }>'.
      Property 'isStream' is missing in type '{ method: Method; url: string; searchParams: string; json: { [key: string]: any; }; headers: Headers; responseType: ResponseType; hooks: { beforeRequest: (() => Promise<void>)[]; beforeRetry: ((options: NormalizedOptions, error: GeneralError, retryCount: number) => Promise<...>)[]; }; }' but required in type '{ isStream: true; }'.
```

**Comment by szmarczak** [comment] 2020-03-16 15:18
Possibly a duplicate of #954

**Closed** 2020-04-01 16:02 UTC
