### ISSUE TITLE
Get original response on error

### ISSUE THREAD

**Issue by sutkh** [sindresorhus/got#380] opened 2017-09-26 02:37 UTC
Is it currently possible to get the response object when a request fails? I'm interested in getting the body of the response, despite the fact that it failed, but I don't see an obvious way to do so

**Comment by sindresorhus** [comment] 2017-09-26 03:58
Duplicate of https://github.com/sindresorhus/got/pull/372

**Closed by sindresorhus** 2017-09-26 03:58 UTC
