### ISSUE TITLE
Empty response body

### ISSUE THREAD

**Issue by akopchinskiy** [sindresorhus/got#1371] opened 2020-07-22 16:04 UTC
#### Describe the bug

Empty body in response after a POST request.

```ts
const response1= await got.post(AUTH_API_URL, {
                json: {
                    password: 'password'
                },
                responseType: 'json',
                headers: {'Content-Type': 'application/json'}
            });

console.log(response1.body);  // Empty string: ""

const response2 = await Axios.post(AUTH_API_URL, {password: 'password'}, {
                headers: {'Content-Type': 'application/json'}
            });

console.log(response2.data);  // All ok: { token: "........." }

```

 - Node.js version: 
 - OS & version: 

Win 10;
Node: v14.0.0;
Npm: 6.14.4;
got: 11.3.0;

**Comment by akopchinskiy** [comment] 2020-07-22 17:43
Reverting back to `10.7.0` fixed the issue. So it's definitely a bug.

**Comment by szmarczak** [comment] 2020-07-22 18:58
> got: 11.3.0;

Why are you using an outdated version of Got? The current one is 11.5.1.

**Comment by szmarczak** [comment] 2020-07-22 19:01
> Node: v14.0.0;

Please update your Node.js version.
Duplicate of #1349

**Closed by szmarczak** 2020-07-22 19:01 UTC

**Comment by akopchinskiy** [comment] 2020-08-06 16:29
@szmarczak why did you close the issue? I did mistype. The version was 11.5+
And why I need to update Node if only your package doesn't work?

**Comment by szmarczak** [comment] 2020-08-06 17:09
https://github.com/sindresorhus/got/issues/1349#issuecomment-655564832
