### ISSUE TITLE
v11 and un-mocked nock request: socker hang up error

### ISSUE THREAD

**Issue by avaly** [sindresorhus/got#1226] opened 2020-05-06 10:34 UTC
#### Describe the bug

- `got` version: 11.1.1
- `nock` version: 12.0.3
- Node.js version: 12.16.3
- OS & version: Ubuntu 18.04.4

When `got` is used together with `nock`, but the request that `got` makes is not defined in `nock` (e.g. nock mocks a different path), an unexpected error is thrown: `socket hang up`.

This did not happen in got v10 with the same `nock` version.

#### Actual behavior

```
$ node got-bug-report.js 
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at InterceptedRequestRouter.handleAbort (/home/dev/node_modules/nock/lib/intercepted_request_router.js:200:28)
    at OverriddenClientRequest.req.abort (/home/dev/node_modules/nock/lib/intercepted_request_router.js:79:35)
    at PromisableRequest._destroy (/home/dev/node_modules/got/dist/source/core/index.js:1026:32)
    at PromisableRequest.destroy (internal/streams/destroy.js:38:8)
    at PromisableRequest.<anonymous> (/home/dev/node_modules/got/dist/source/as-promise/index.js:188:25)
    at Object.onceWrapper (events.js:300:26)
    at PromisableRequest.emit (events.js:210:5)
    at PromisableRequest._beforeError (/home/dev/node_modules/got/dist/source/as-promise/core.js:113:14)
    at OverriddenClientRequest.<anonymous> (/home/dev/node_modules/got/dist/source/core/index.js:766:18)
    at Object.onceWrapper (events.js:300:26)
Emitted 'error' event on OverriddenClientRequest instance at:
    at /home/dev/node_modules/nock/lib/intercepted_request_router.js:108:11
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  code: 'ECONNRESET'
}
```

#### Expected behavior

Using `axios` and `nock` the same sample code results in this error:

```
$ node got-bug-report.js 
Error Error: Nock: No match for request {
  "method": "GET",
  "url": "https://example.com/bar",
  "headers": {
    "accept": "application/json, text/plain, */*"
  }
}
```

#### Code to reproduce

```js
// const axios = require('axios');
const got = require('got');
const nock = require('nock');

nock.disableNetConnect();

function run() {
  nock('https://example.com').get('/foo').reply(200);

  return got('https://example.com/bar');
  // return axios('https://example.com/bar');
}

run().catch(err => console.error('Error', err));
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment] 2020-05-06 13:16
Duplicate of #1224

**Closed by szmarczak** 2020-05-06 13:16 UTC

**Comment by mastermatt** [comment] 2020-05-06 16:06
This is being track in Nock here: https://github.com/nock/nock/issues/1992
