### ISSUE TITLE
"RequestError: connect ECONNREFUSED" from got when also requiring node-mailjet

### ISSUE THREAD

**Issue by ripperdoc** [sindresorhus/got#1515] opened 2020-10-28 13:54 UTC
#### Describe the bug

 - Node.js version: 14.8.0
 - OS & version: MacOs 10.14.5

The packages `got` and `node-mailjet` somehow interact to create a bug that throws on all `got`-requests. I don't understand what's going on under the hood so I report this potential bug both here and over at `node-mailjet`. 

#### Actual behavior

`got("https://google.com")` throws `RequestError: connect ECONNREFUSED`. Full stack trace:
```
RequestError: connect ECONNREFUSED 127.0.0.1:443
    at ClientRequest.<anonymous> (/Users/martin/dev/src/test/node_modules/got/dist/source/core/index.js:953:111)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:326:22)
    at ClientRequest.origin.emit (/Users/martin/dev/src/test/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  code: 'ECONNREFUSED',
  timings: {
    start: 1603894700629,
    socket: 1603894700629,
    lookup: 1603894700630,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1603894700630,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 1,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 1
    }
  }
}
```

#### Expected behavior

That it would respond with data.

#### Code to reproduce
Setup a fresh npm package with the following code and ran:
```js
// index.js
async function test() {
    const got = require('got');
    const mailjet = require("node-mailjet");
    try {
        console.log(await got("https://google.com"));
    } catch (e) {
        console.error(e);
    }}

test();
// package.json
{
  "name": "test",
  "main": "index.js",
  "dependencies": {
    "got": "11.8.0",
    "node-mailjet": "3.3.1"
  }
}


```
If I comment out the mailjet require, the code works as expected, so the likely culprit is node-mailjet, but perhaps it has some impact what's happening in got's code as well.
#### Checklist

- [ x ] I have read the documentation.
- [ x ] I have tried my code with the latest version of Node.js and Got.

**Comment by ripperdoc** [comment] 2020-10-28 14:04
I might add that `node-mailjet` uses `superagent` and a proxy that patches `superagent.Request`, if that means something.

**Comment by Giotino** [comment] 2020-10-28 14:11
> I might add that `node-mailjet` uses `superagent` and a proxy that patches `superagent.Request`, if that means something.

Yeah, it could be. Your error is about an invalid certificate, but it has nothing to do with the certificate.
Actually when importing `node-mailjet` all the requests goes to `127.0.0.1:433` (you probably have an HTTPS server on localhost, hence the invalid certificate).

**Comment by ripperdoc** [comment] 2020-10-28 14:19
Yes, you are right, I'm running a local server. Let me update the report with the error message if not running a local server, to avoid misleading.

**Comment by ripperdoc** [comment] 2020-10-28 14:25
I can also add that this error doesn't appen if I use node `https` instead of `got`, as per this test code:

```js
async function test() {
    const mailjet = require("node-mailjet");
    const got = require('got');
    // try {
    //     console.log(await got("https://google.com"));
    // } catch (e) {
    //     console.error(e);
    // }}
    const https = require("https");
    https.get('https://google.com', (res) => {
        res.on('data', (d) => {
            process.stdout.write(d);
        });
        }).on('error', (e) => {
            console.error(e);
        });
}

test();
```

**Comment by Giotino** [comment] 2020-10-28 14:28
The culprit is this line:
https://github.com/mailjet/mailjet-apiv3-nodejs/blob/332c9584711ecd8ef1ed9d5d076730dae43f232b/mailjet-client.js#L48

But `superagent-proxy` only add a `proxy` function to `superagent.Request` (in the case of `node-mailjet`)

**Comment by Giotino** [comment] 2020-10-28 14:48
Just by requiring `proxy-agent`

**Comment by szmarczak** [comment] 2020-10-28 16:28
Duplicate of #1463 #1429 #982 #951

**Closed by szmarczak** 2020-10-28 16:28 UTC
Labels: external
