### ISSUE TITLE
Lowercase headers choice

### ISSUE THREAD

**Issue by yovanoc** [sindresorhus/got#1335] opened 2020-06-30 14:17 UTC
#### What problem are you trying to solve?

The server we try to access verify the case of the headers. eg: lowercase doesn't work

#### Describe the feature

Could be a good idea to have the choice to lowercase or not the headers, thanks

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by sindresorhus** [comment] 2020-06-30 15:44
> The server we try to access verify the case of the headers. eg: lowercase doesn't work

Then the server is not following the HTTP spec. You should report it to them no matter the outcome of this issue.

**Comment by yovanoc** [comment] 2020-06-30 15:55
Yes is more like an anti-bot/spam

**Comment by szmarczak** [comment] 2020-06-30 18:45
Duplicate of #231 #50 #1103 #1155. Closing. Please don't open issues that have been already solved.

**Closed by szmarczak** 2020-06-30 18:45 UTC

**Comment by xamgore** [comment] 2020-08-12 10:20
@yovanoc you may register a custom handler via `got.extend` and pass the required headers there.
