### ISSUE TITLE
Timeout option not working with proxy (using tunnel as proxy)

### ISSUE THREAD

**Issue by shikar** [sindresorhus/got#1394] opened 2020-08-06 17:43 UTC
#### Describe the bug

 - Node.js version: 
 - OS & version: 

#### Actual behavior

I know timeout is milliseconds!
My question is Timeout option not working with proxy (using tunnel as proxy)

#### Expected behavior

Timeout option is not work, when i add 'proxy agent' option
if i remove 'proxy agent', timeout is work.
but I need them both, and how could i figure it out?

#### Code to reproduce

```js
got('https://example.com', {
    timeout: 50,
    agent: {
        https: tunnel.httpsOverHttp({
             proxy: {
                 host: '175.44.108.137',
                 port: 9999
            }
        })
    }
})
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment] 2020-08-06 18:57
Duplicate of #1393

**Closed by szmarczak** 2020-08-06 18:57 UTC
