### ISSUE TITLE
If the response stream is not fully consumed in for-await-of loop, then the code after the loop is not executed

### ISSUE THREAD

**Issue by mikeconley12** [sindresorhus/got#1328] opened 2020-06-24 20:20 UTC
#### Describe the bug

 - Node.js version: v14.4.0
 - OS & version: Ubuntu 18.04.4

If the response stream is not fully consumed in for-await-of loop, then the code after the loop is not executed

#### Actual behavior

The code prints:

```
before loop
```

#### Expected behavior

The code should print:

```
before loop
after loop
```

#### Code to reproduce

```js
const got = require("got");

got
  .stream("https://www.google.com/")
  .on("response", async response => {
    console.log("before loop");
    for await (const chunk of response) {
      break;
    }
    console.log("after loop"); // this line is not executed
  });
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment] 2020-06-24 20:57
Duplicate of #223 https://github.com/sindresorhus/got/issues/223#issuecomment-405076226

**Closed by szmarczak** 2020-06-24 20:57 UTC
