### ISSUE TITLE
Problem running on Safari and FireFox, Chrome works fine

### ISSUE THREAD

**Issue by pgiani** [sindresorhus/got#263] opened 2017-01-20 14:04 UTC
Im using your package as a dependency on my meteor project and it break the app on FireFox and Safary

![error](https://cloud.githubusercontent.com/assets/5713173/22152124/53a2e5ea-deef-11e6-9aba-625b8eee165e.png)

The problem is on line 323
`for (const el of helpers) {`

if you can change it to this, it works on safary and Firefox

`for (var el of helpers) {`

Thank you

**Comment by sindresorhus** [comment] 2017-01-20 14:30
Duplicate of https://github.com/sindresorhus/got/issues/259.

**Closed by sindresorhus** 2017-01-20 14:30 UTC

**Comment by pgiani** [comment] 2017-01-20 14:56
Thanks
