### ISSUE TITLE
Ignored NODE_TLS_REJECT_UNAUTHORIZED environment variable

### ISSUE THREAD

**Issue by patoi** [sindresorhus/got#2177] opened 2022-11-10 12:42 UTC
#### Describe the bug

 - Node.js version: v16, v18 LTS
 - OS & version: Ubuntu Linux 22.04

With `NODE_TLS_REJECT_UNAUTHORIZED='0'`, Node.js http module request method ignores TLS handshake error, e.g: request a test webserver with production webserver certificate.

In got v11, it works as Node.js http request.

In got v12.5.2, occurs an error, because `NODE_TLS_REJECT_UNAUTHORIZED='0'` is ignored.

#### Actual behavior

In got v12.5.2, occurs an error, because `NODE_TLS_REJECT_UNAUTHORIZED='0'` is ignored.

#### Expected behavior

The got v12 does not throw TLS error, when `NODE_TLS_REJECT_UNAUTHORIZED='0'`

#### Code to reproduce

https://github.com/patoi/bug-got-NODE_TLS_REJECT_UNAUTHORIZED

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment] 2022-11-11 23:14
Duplicate of #2149

**Closed by szmarczak** 2022-11-11 23:14 UTC

**Comment by patoi** [comment] 2022-11-12 10:54
@szmarczak  Thanks for taking care of it! I can see that this is by-design. It might be worth adding it to the documentation as a breaking change (in v11 it worked differently).
