### ISSUE TITLE
JSON mode - got.post(...).json is not a function

### ISSUE THREAD

**Issue by daaru00** [sindresorhus/got#780] opened 2019-04-16 20:47 UTC
#### Describe the bug

 - Node.js version: v8.10
 - OS & version: AWS Lambda

 - Node.js version: v10.15.2
 - OS & version: Linux

I followed the documentation about [JSON mode](https://github.com/sindresorhus/got#json-mode) but the code snippet raise and error:
```
TypeError: got.post(...).json is not a function
```

#### Actual behavior

`.json()` function raise an error

#### Expected behavior

made an HTTP request with POST method and response type `application/json`

#### Code to reproduce

https://repl.it/@daaru00/got-post-request-error

```js
const got = require('got');

(async () => {
	const {body} = await got.post('https://httpbin.org/anything', {
		body: {
			hello: 'world'
		}
	}).json();

	console.log(body);
	//=> {...}
})();
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by daaru00** [comment] 2019-04-16 21:05
The entire section of [JSON mode](https://github.com/sindresorhus/got#json-mode) seems not working, trying the first snippet:
```js
const got = require('got');

(async () => {
	const response = await got.post('https://httpbin.org/anything', {
		body: {
			hello: 'world'
		},
		responseType: 'json'
	});

	console.log(response.body.data);
	//=> '{"hello":"world"}'
})();
```
raise an other error:
```
TypeError: The `body` option must be a stream.Readable, string or Buffer
```
Seems the default are different from a json-ready request and response.

## Workaround
If I use the `json` option it works:
```js
const got = require('got');

(async () => {
	const response = await got.post('https://httpbin.org/anything', {
                json: true, // this is required
		body: {
			hello: 'world'
		}
	}); // .json() still not working

	console.log(response.body.data);
	//=> '{"hello":"world"}'
})();
```

**Comment by sindresorhus** [comment] 2019-04-17 02:23
Duplicate of #713

**Closed by sindresorhus** 2019-04-17 02:23 UTC

**Comment by sindresorhus** [comment] 2019-09-17 09:31
We have an alpha version of v10 out if you wanna help us test: https://github.com/sindresorhus/got/releases/tag/v10.0.0-alpha.1
