### ISSUE TITLE
Buffer.from is not exists in node 4.5-

### ISSUE THREAD

**Issue by tommytroylin** [sindresorhus/got#242] opened 2016-11-04 05:35 UTC
`Buffer.from(string,'binary')` function is first added in **node 4.5** 

on node 4.4.4 it will throw `TypeError: binary is not a function`

FYI.
[Node 4.4.4 Buffer API](https://nodejs.org/dist/v4.4.4/docs/api/buffer.html)
[Node 4.5.0 Buffer API](https://nodejs.org/dist/v4.5.0/docs/api/buffer.html)

Seems like
[this commit](https://github.com/sindresorhus/got/commit/5888ca7aa1ca982caac27e7796e225f70ded68a4) will break this module on node4.5-

**Comment by shinnn** [comment] 2016-11-04 05:57
Duplicate of https://github.com/sindresorhus/got/issues/241

Use 4.5.0 or newer.

**Closed by shinnn** 2016-11-04 05:57 UTC
