### ISSUE TITLE
Getting Errors on HTTPS / LTS, unsigned certificates and disabled authorization

### ISSUE THREAD

**Issue by lifely** [sindresorhus/got#2199] opened 2022-12-19 23:32 UTC
#### Describe the bug

 - Node.js version:  v18.0.0
 - OS & version: macOS 13.0.1

There an issue on `LTS` and `HTTP` error while I have `authorization` disabled. 

#### Actual behavior

While using @mgcrea/node-tydom-client im running into new "TLS" issue for localhost request.
The client only use `get` requests from `got`, I have `NODE_TLS_REJECT_UNAUTHORIZED=0` configured.

However my request still get denied, with the following error:

```
(node:8950) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)

/Users/lifely/Desktop/playground/tydom/node_modules/got/dist/source/core/index.js:970
            error = error instanceof timed_out_1.TimeoutError ? new TimeoutError(error, this.timings, this) : new RequestError(error.message, error, this);
                                                                                                              ^
RequestError: write EPROTO 00A5B50E02000000:error:0A000152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled:../deps/openssl/openssl/ssl/statem/extensions.c:908:

    at ClientRequest.<anonymous> (/Users/lifely/Desktop/playground/tydom/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (node:events:642:26)
    at ClientRequest.emit (node:events:539:35)
    at ClientRequest.emit (node:domain:475:12)
    at ClientRequest.origin.emit (/Users/lifely/Desktop/playground/tydom/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
```

I've tried setting up `global-agent` to debug what's going on, but the request works find going through my local proxy.

#### Expected behavior

The request should works both with or with-out proxy.

**Comment by ChicknTendr** [comment] 2022-12-19 23:35
It looks like you are encountering an error when making HTTPS requests using the got library in a Node.js application. The error message indicates that there is an issue with TLS (Transport Layer Security) and that there was a problem with the certificate verification process.

The error message also mentions that the NODE_TLS_REJECT_UNAUTHORIZED environment variable is set to '0', which disables certificate verification and makes TLS connections and HTTPS requests insecure. This is why you are seeing the warning about making TLS connections and HTTPS requests insecure by disabling certificate verification.

To resolve this issue, you will need to ensure that the certificate verification process is functioning correctly. This could involve:

1. Make sure that you are using the correct certificate for the HTTPS server you are trying to connect to. The certificate should be issued by a trusted certificate authority (CA) and should be valid for the domain you are trying to connect to.

2. Check the certificate chain to make sure it is properly trusted by your application. The certificate chain includes the certificate for the HTTPS server you are trying to connect to, as well as any intermediate certificates that are required to establish trust.

3. Check the certificate itself to make sure it is valid and not expired. You can use a tool like openssl to check the details of the certificate.

4. Make sure that the NODE_TLS_REJECT_UNAUTHORIZED environment variable is not set to '0', as this disables certificate verification and makes TLS connections and HTTPS requests insecure.

5. If you are using a self-signed certificate, you may need to add the certificate to the list of trusted certificates on your system.

If the problem persists, you may want to try using a different HTTPS library, such as request or axios, to see if the issue is specific to the got library.

**Comment by szmarczak** [comment] 2023-01-22 10:48
Got does not follow environment variables. You have to pass `https.rejectUnauthorized: false` directly.

Duplicate of #2149

**Closed by szmarczak** 2023-01-22 10:48 UTC
