### ISSUE TITLE
Got response bodies are empty on WSL

### ISSUE THREAD

**Issue by Sesamestrong** [sindresorhus/got#1395] opened 2020-08-06 22:17 UTC
#### Describe the bug

 - Node.js version: 14.0.0
 - OS & version: 

This bug causes an empty response body to be returned from some requests when using WSL. I've only found it to be a problem with one website, so I don't think it's universal, but it breaks my project on WSL. I have tried running this on WSL, Ubuntu, Windows native (via Powershell), Runkit, Repl.it and a few other online VM-based solutions; WSL is the only one causing an empty body to be returned.

#### Actual behavior
The request returns a JSON object.
...

#### Expected behavior
The request returns an empty string.
...

#### Code to reproduce

```js
require("got")
  .post("http://jsnice.org/beautify", { searchParams:{pretty: 0, rename: 0, types: 0, suggest: 1},body:"console.log('example request body')" })
  .json()
  .then(b=>console.log(b));
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment] 2020-08-06 22:35
Duplicate of #1371 #1349

**Closed by szmarczak** 2020-08-06 22:35 UTC
