### ISSUE TITLE
TypeError: The payload has been already provided

### ISSUE THREAD

**Issue by pavannarayan05** [sindresorhus/got#2033] opened 2022-04-20 16:32 UTC
#### Describe the bug

 - Node.js version: 17.7.1
 - OS & version: Linux

I am using node v17 and got 12.0.3. I am trying to upload a stream using got.stream.post.
I am getting the below error even when I use a small file (1kb) to upload. 

TypeError: The payload has been already provided at Request.onLockedWrite got
(/app/node_modules/got/dist/source/core/index.js:696:19)

I see below comments in the 'got' module - node_modules/got/dist/source/core/index.js:

 // TODO: Remove this when targeting Node.js >= 12

Can you please suggest whats causing this issue and which lines need to be removed when using node v17 (>12).
Let me know if you have any other alternative solutions

#### Expected behavior
Stream upload using got.stream.post should be successful without any error from got

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment] 2022-04-25 00:58
Duplicate of #2009

**Closed by szmarczak** 2022-04-25 00:58 UTC
