### ISSUE TITLE
Library erroneously URI-encodes usersname and password

### ISSUE THREAD

**Issue by JoshuaWise** [sindresorhus/got#2093] opened 2022-07-28 16:05 UTC
#### Describe the bug

When `Got` builds an `Authorization` header for basic auth, it URI-encodes the username and password. This is not warranted by any spec, and it breaks requests that use special characters in their username or password.

#### Actual behavior

Got URI-encodes the username and password used in the `Authorization` header for basic auth.

#### Expected behavior

Got should send whatever username or password is specified by the user, without modification.

#### Code to reproduce

```js
const client = Got.extend({
  username: process.env.AUTH_USER,
  password: process.env.AUTH_PASS,
});

await client.get(url);
```

#### Checklist

- [x] I have read the documentation.
- [ ] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment] 2022-07-28 16:58
https://github.com/sindresorhus/got/blob/e032b60ff3285403b8f9627dcdd32aae39867d7a/source/core/options.ts#L1842-L1883
https://github.com/sindresorhus/got/blob/e032b60ff3285403b8f9627dcdd32aae39867d7a/source/core/index.ts#L1044
https://github.com/sindresorhus/got/blob/e032b60ff3285403b8f9627dcdd32aae39867d7a/source/core/index.ts#L1060-L1063

show otherwise. Can you please post an actual code to reproduce the issue? The one you posted isn't valid.

**Comment by JoshuaWise** [comment] 2022-07-28 19:42
I can reproduce the bug in v11.8.5, but not v12.3.0. I can't upgrade to version 12 because using ES modules would require an entire refactor of our build system.

**Comment by JoshuaWise** [comment] 2022-07-28 19:42
Here's how to reproduce:
```
'use strict';
const http = require('http');
const Got = require('got');

const client = Got.extend({
	username: 'admin',
	password: 'special_chars_^#@',
});

const server = http.createServer((req, res) => {
	const auth = req.headers.authorization;
	if (!auth || !auth.startsWith('Basic ')) {
		return res.writeHead(401).end();
	}

	const base64Creds = auth.slice(6);
	const plainCreds = Buffer.from(base64Creds, 'base64').toString();
	const [username, password] = plainCreds.split(':');

	console.log('username: %s\npassword: %s', username, password);

	return res.writeHead(204).end();
});

server.listen(0, () => {
	const { port } = server.address();

	client.get(`http://localhost:${port}`).finally(() => server.close());
});

```

**Comment by szmarczak** [comment] 2022-07-29 13:05
https://github.com/sindresorhus/got/blob/5e17bb748c260b02e4cf716c2f4079a1c6a7481e/source/core/index.ts#L1690-L1702

In Got v11 we don't do any special handling. The bug is in upstream, see https://github.com/nodejs/node/pull/31450

Duplicate of #1169

**Closed by szmarczak** 2022-07-29 13:05 UTC
