### ISSUE TITLE
Module not found: Can't resolve.. when adding to angular project 

### ISSUE THREAD

**Issue by amritzz** [sindresorhus/got#368] opened 2017-09-04 23:40 UTC
Hi,

I am facing an error when trying to include a package using this library: More details here: [Here](https://github.com/vankasteelj/trakt.tv/issues/47)

The Error I receive is: ERROR in ./node_modules/trakt.tv/node_modules/got/index.js
Module not found: Error: Can't resolve './package' in 'C:\clientApp\node_modules\trakt.tv\node_modules\got'

Any help would be appreciated, thanks

**Comment by sindresorhus** [comment] 2017-09-05 02:20
Duplicate of https://github.com/sindresorhus/got/issues/363
Duplicate of https://github.com/sindresorhus/got/issues/266
Duplicate of https://github.com/sindresorhus/got/pull/349

**Closed by sindresorhus** 2017-09-05 02:20 UTC
