### ISSUE TITLE
Loosen Node LTS support requirement

### ISSUE THREAD

**Issue by hershmire** [sindresorhus/got#1294] opened 2020-05-27 18:32 UTC
#### What would you like to discuss?

I noticed that Got is requiring the latest patch of Node 10 (currently `"node": ">=10.19.0"` https://github.com/sindresorhus/got/blob/master/package.json#L10). I'm curious if this can be loosened to support any version of Node 10 (`"node": ">=10"`) which would allow this to be used in Node JS runtimes that take longer to upgrade – i.e. Firebase Functions which is currently at 10.18.1 (https://cloud.google.com/functions/docs/concepts/nodejs-10-runtime). 

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment] 2020-05-27 21:45
Duplicate of #1084 #1130 #1260

**Closed by szmarczak** 2020-05-27 21:45 UTC
