### ISSUE TITLE
tsc can't resolve types for got 13

### ISSUE THREAD

**Issue by trim21** [sindresorhus/got#2267] opened 2023-05-27 19:08 UTC
#### Describe the bug

 - Node.js version: node18
 - OS & version: doesn't matter

got 13 types exports breaks tsconfig.json `"moduleResolution": "Node"` and package.json `"type": "module"`

#### Actual behavior
```text
index.ts:1:22 - error TS2307: Cannot find module 'got' or its corresponding type declarations.

1 import * as got from 'got'
                       ~~~~~


Found 1 error in index.ts:1
```

#### Expected behavior

should resolve types

...

#### Code to reproduce

```ts
import * as got from 'got'
```

re-produce repo:

https://github.com/trim21/got-type

#### Checklist

- [X] I have read the documentation.
- [X] I have tried my code with the latest version of Node.js and Got.

fix:
```diff
--- a/package.json
+++ b/package.json
@@ -6,8 +6,8 @@
 	"repository": "sindresorhus/got",
 	"funding": "https://github.com/sindresorhus/got?sponsor=1",
 	"type": "module",
+	"types": "./dist/source/index.d.ts",
 	"exports": {
-		"types": "./dist/source/index.d.ts",
 		"default": "./dist/source/index.js"
 	},
 	"engines": {
```

**Comment by sindresorhus** [comment] 2023-05-27 19:38
Got has been an ESM package since v12. You must have [`"module": "node16", "moduleResolution": "node16"` in your tsconfig](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-make-my-typescript-project-output-esm).

**Comment by sindresorhus** [comment] 2023-05-27 19:38
> import * as got from 'got'

Got is a default export:

```js
import got from 'got';
```

**Comment by trim21** [comment] 2023-05-27 20:05
saidly, I can't do that... I'd like to use `"moduleResolution": "node16"` but there are some packages I'm 
 using doesn't support it...

**Comment by lucgagan** [comment] 2023-05-29 02:13
Heads up that node16 module resolution does not work in Next.js projects.

**Comment by trim21** [comment] 2023-05-29 02:19
Another sulution is to upgrade typescript to 5.0 and set `moduleResolution` to `bundler`, if you are using any bundler (including nodejs esm loader or nodejs register) instead of simple run code generated by `tsc`

**Comment by asfo** [comment] 2023-05-29 15:23
I hope that the fix goes in, we are not able to use `got` on `v13` without that fix in our current project, but with the fix everything works well.

**Comment by Hacksore** [comment] 2023-05-29 16:04
So in the context of nextjs I'm not entirely sure there is a good path to support `moduleResolution: node16`.

I created two branches with examples in the following repo one without ESM reproducing the similar issue we see here and one with ESM/node16.
https://github.com/Hacksore/got-13-type-woes/tree/master
https://github.com/Hacksore/got-13-type-woes/tree/use-node16

The second branch is where I attempted to follow what @sindresorhus was saying and update the `tsconfig.json`.

With the ESM port I get errors when importing from the `next` package.

```
use-node16 ✔ $ yarn build
yarn run v1.22.19
$ next build
- warn Compiled with warnings

./node_modules/keyv/src/index.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/keyv/src/index.js
./node_modules/cacheable-request/dist/index.js
./node_modules/got/dist/source/core/index.js
./node_modules/got/dist/source/index.js
./src/app/api/bug/route.ts

- info Linting and checking validity of types .Failed to compile.

./src/app/page.tsx:1:19
Type error: Cannot find module 'next/image' or its corresponding type declarations.

> 1 | import Image from 'next/image'
    |                   ^
  2 | import styles from './page.module.css'
  3 | 
  4 | export default function Home() {
error Command failed with exit code 1.
```

**Comment by Hacksore** [comment] 2023-05-29 16:11
related next issue https://github.com/vercel/next.js/issues/46078

**Comment by lucgagan** [comment] 2023-05-29 20:02
For context, my attempt at adding node16 support to next.js

https://github.com/vercel/next.js/pull/50357

I don't think it is possible to make it work using the current setup.

**Comment by igorovic** [comment] 2023-05-30 12:05
I am wondering what could go wrong with this solution ? 

```json
{
	"name": "got",
	"version": "13.0.0",
	"description": "Human-friendly and powerful HTTP request library for Node.js",
	"license": "MIT",
	"repository": "sindresorhus/got",
	"funding": "https://github.com/sindresorhus/got?sponsor=1",
	"type": "module",
	"types": "./dist/source/index.d.ts",
	"exports": {
		"types": "./dist/source/index.d.ts",
		"default": "./dist/source/index.js"
	},

``` 

Until `got` version 12.6.0 `types` attribute was present in `package.json`. 
![image](https://github.com/sindresorhus/got/assets/758832/ca0f28d1-34fb-4b79-8099-8169e5ae06a9)

In version 13.0.0 it was removed. 

If I manually restore this line it works with nextjs 13. 

Is there any potential issue restoring the `types` attribute ?

**Comment by aPoCoMiLogin** [comment] 2023-05-31 16:34
this change also breaks webstorm autocomplete

**Comment by Stanzilla** [comment] 2023-05-31 22:20
My builds also started failing on v13 with `error TS2307: Cannot find module 'got' or its corresponding type declarations.`

**Comment by tzbo** [comment] 2023-05-31 22:46
Same problem

**Comment by ClementValot** [comment] 2023-06-02 07:18
It also breaks [tsoa](https://github.com/lukeautry/tsoa) route generation which makes use of the typescript library `TypeResolvers` and `isIndexedAccessTypeNode`-like methods 

```
 GenerateMetadataError: Could not determine the keys on PlainResponse
At: myProject\src\MyRoute.ts:28:28.
This was caused by 'statusCode: PlainResponse['statusCode'];'
    at TypeResolver.resolve (myProject\node_modules\@tsoa\cli\dist\metadataGeneration\typeResolver.js:314:23)
```

**Comment by svsool** [comment] 2023-06-06 12:47
same problem as well

**Comment by FabianFrank** [comment] 2023-06-07 18:06
> Got has been an ESM package since v12. You must have [`"module": "node16", "moduleResolution": "node16"` in your tsconfig](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-make-my-typescript-project-output-esm).

v12 works with `moduleResolution: "node"` in ESM projects, v13 does not and requires `node16`.

**Comment by datner** [comment] 2023-06-08 07:50
ESM is still dead in the water for 99% of real-world projects. Which is an improvement from 100% of like a year back.
But it doesn't mean you have to skip updating `got`. 
This is my `tsconfig`:
```json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "compilerOptions": {
    "baseUrl": ".",
    "module": "CommonJS",
    "moduleResolution": "node",
    "isolatedModules": true,
    "esModuleInterop": true,
    "strict": true,
    "downlevelIteration": true,
    "paths": {
      "~/*": [
        "./src/*"
      ],
      "got": ["./node_modules/got/dist/source"]
    }
  }
}
```

**Comment by terchris** [comment] 2023-06-08 14:58
Did the required changes to get got package working. But now the packages slugify and sizeOf don't work.

"module": "node16",                      // Changed this line from "ESNext" to "node16" To use got package     
"moduleResolution": "node16",            // Changed this line from "node" to "node16"  To use got package

**Comment by Hacksore** [comment] 2023-06-10 15:56
@datner's solution will work for nextjs as long as you are not converteting next to use ESM.

You will still get the warning:
```
- warn Compiled with warnings

./node_modules/keyv/src/index.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/keyv/src/index.js
./node_modules/cacheable-request/dist/index.js
./node_modules/got/dist/source/core/index.js
./node_modules/got/dist/source/index.js
./src/app/api/bug/route.ts
```

[example source](https://github.com/Hacksore/got-13-type-woes/tree/add-got-type-defs)

**Comment by datner** [comment] 2023-06-10 16:02
> converteting next to use ESM.

as far as I know, nextjs do not support and are not planning or intending to support esm, so I am not surprised that `got` and most probably others won't work without more extensive hacking 😄  

in general, it's really quite confusing that everyone supports the `import` syntax or browser es modules. But practically no one supports node16 esm

**Comment by trim21** [comment] 2023-06-10 16:05
or you can [patch](https://github.com/ds300/patch-package) got

**Comment by datner** [comment] 2023-06-10 16:21
@trim21 share the patch then

**Comment by trim21** [comment] 2023-06-10 16:23
> @trim21 share the patch then

read the issue description again

**Comment by Hacksore** [comment] 2023-06-10 16:39
Here is the `patch-package` example

https://github.com/Hacksore/got-13-type-woes/tree/use-patch-package

**Comment by datner** [comment] 2023-06-10 17:21
oops!

**Comment by ClementValot** [comment] 2023-06-11 00:44
I'm still confused as to why `"moduleResolution": "NodeNext"` would cause compatibility issues compared to `Node16`

The documentation is rather scarce on the subject but tends to suggest `NodeNext` includes `Node16` behavior, is there anyone more seasoned on the subject who can help me understand?

**Comment by igorovic** [comment] 2023-06-12 06:59
My undestanding is that for NodeJs the following is perfectly fine. 

```json
"type": "module",
"exports": {
    "types": "./dist/source/index.d.ts",
    "default": "./dist/source/index.js"
},
```

It tells nodejs that this is a esm package. Actually Nodejs in this case does not care about the `types` information.

However, from typescript perspective `types deifinitions` are relevant. And in this case TS thinks it's only an esm pacakge and there is probably some module resolution conflicts in Nextjs environment. 

Since only TS cares about `types` I think patching `package.json` like in the snippet below should be fine. 

```json
"type": "module",
"types": "./dist/source/index.d.ts",
"exports": {
    "types": "./dist/source/index.d.ts",
    "default": "./dist/source/index.js"
},
```
With this patch, I assume that TS will fallback to search types definitions in the root property `types` when it finds that it's not in a `type=module` environment. Which is the case when using NextJS. 
This is actually the patch I use. 

Another possible solution would be to define both `exports`. for `esm` and for `commonjs`. Something like: 

```json
"type": "module",
    "exports": {
        ".": {
            // Entry-point for `import "my-package"` in ESM
            "import": {
                // Where TypeScript will look.
                "types": "./dist/source/index.d.ts",
                // Where Node.js will look.
                "default": "./dist/source/index.js"
            },
            // Entry-point for `require("my-package")` in CJS
            "require": {
                // Where TypeScript will look.
                "types": "./dist/source/index.d.ts",
                // Where Node.js will look.
                "default": "./dist/source/index.js"
            },
        }
    },
```
I haven't tested it. 




--- 
## References
https://nodejs.org/api/packages.html
[Typescript doc](https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing)

**Comment by JaneJeon** [comment] 2023-06-29 12:27
Seeing this as well, even with a vanilla js workspace w/ "type": "module" set. Suspecting it has to do with the lack of "types" specification in package.json :(

**Comment by Pipe-Runner** [comment] 2023-07-09 08:18
> ```json
> "got": ["./node_modules/got/dist/source"]
> ```

This seems to unblock the build for me. Thank you.

**Comment by alvis** [comment] 2023-07-13 22:04
We should continue to push the wave of ESM, but removing the `types` field doesn't seem to be the way for me.
There are just so many constraints in the real world that disallow us to use `node16` in the foreseeable future

**Comment by Hacksore** [comment] 2023-07-13 22:26
I think it's pretty clear that @sindresorhus's packages are [ESM only](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) without plans to make any future CJS.

Not sure [the types](https://arethetypeswrong.github.io/?p=got%4013.0.0) will ever be accommodating for the crazy world of ESM v CJS but at least we have workarounds.

**Comment by baptisteArno** [comment] 2023-07-14 16:54
Same... `"moduleResolution": "Node16"` just introduced other issue in my next.js projects. For now, I have to revert to v12

**Comment by throrin19** [comment] 2023-07-20 14:57
Same with `"moduleResolution": "node"`

**Comment by conioX** [comment] 2023-07-22 03:09
why we need support this esm :( most framework dont support this esm

**Comment by hugo082** [comment] 2023-08-01 07:57
For those who wants to disable the warning, please refer to https://github.com/vercel/next.js/discussions/49432 and https://github.com/jaredwray/keyv/issues/45:
```
- warn Compiled with warnings

./node_modules/keyv/src/index.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/keyv/src/index.js
./node_modules/cacheable-request/dist/index.js
./node_modules/got/dist/source/core/index.js
./node_modules/got/dist/source/index.js
./src/app/api/bug/route.ts
```

You can override the webpack configuration with:
```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  // ...
  webpack: (config) => {
    // Ignore ALL webpack warnings produced by ./node_modules/keyv/src/index.js file
    config.ignoreWarnings = [
      { module: /node_modules\/keyv\/src\/index\.js/ },
    ];

    return config;
  },
};

module.exports = nextConfig;
```

⚠️ Note that it will **ignore ALL warnings** produced by this file, not only `the request of a dependency is an expression` but you can improve the snippet to filter only this message, please refer to [`ignoreWarnings` documentation](https://webpack.js.org/configuration/other-options/#ignorewarnings)

> Tells webpack to ignore specific warnings. This can be done with a RegExp, a custom function to select warnings based on the raw warning instance which is getting WebpackError and Compilation as arguments and returns a boolean, an object with the following properties:

**Comment by trim21** [comment] 2023-08-01 08:26
> why we need support this esm :( most framework dont support esm

I think the right question is "why intentionally break `"moduleResolution": "Node"`"

**Comment by timeimp** [comment] 2023-08-29 08:58
Typescript 5.2 now explicity fails to build when you mix `module` and `moduleResolutions` in ways you're not meant to.

See https://github.com/microsoft/TypeScript/pull/54567


```
error TS5110: Option 'module' must be set to 'Node16' when option 'moduleResolution' is set to 'Node16'.
```
(or some variation of that).

This means anyone upgrading to 5.2 and using got 13.0.0 will suddenly hit this error.

Using the [above ](https://github.com/sindresorhus/got/issues/2267#issuecomment-1582075262) from @datner, I managed to get a repo working but ran into another error.


The other error - `ERR_UNSUPPORTED_DIR_IMPORT` - had a simple fix.

I used this change to `tsconfig.json`:

```json
"paths": {
    "got": ["./node_modules/got/dist/source/index.js"]
},
```

I figured I'd mention it here now that 5.2 is out and this may become a larger issue before the end of the year.

**Comment by datner** [comment] 2023-08-30 03:23
@timeimp yeah if you use `"module": "Node16"` or `"NodeNext"` then typescript expects full and extensioned imports. No inferring index or skipping the `.js`

**Comment by dandv** [comment] 2023-08-31 16:24
I also [can't get `got` v13 to work with `jest`](https://github.com/kulshekhar/ts-jest/issues/4201). I've tried all sorts of settings mentioned here and in #1952.

**Comment by datner** [comment] 2023-08-31 21:03
@dandv add this to your jest config:
```js
    /**
     * "Not a ts-jest issue" but a jest one. Consider vitest?
     *  this morphs "./some/relative/path.js" to "./some/relative/path"
     *  https://github.com/kulshekhar/ts-jest/issues/1057
     */
    moduleNameMapper: {
        "^(\\.\\.?\\/.+)\\.js$": "$1",
    },
```
Not sure thats exactly it, but I suspect this might help. Maybe.

**Comment by dandv** [comment] 2023-09-01 00:13
@datner: that didn't work, unfortunately. Same error.

**Comment by JoCat** [comment] 2023-09-12 03:29
Great, after updating got, syntax highlighting in VSCode doesn't work. Doesn't matter if it is used:
```
"module": "node16",
"moduleResolution": "node16"
```
![image](https://github.com/sindresorhus/got/assets/13483132/f49e136c-c6a7-4ef4-8c12-d1f9339e88c3)
or not.
![image](https://github.com/sindresorhus/got/assets/13483132/f0a445bc-7aab-462c-88cb-c4162d3340d0)

**Comment by throrin19** [comment] 2023-09-13 06:34
To avoid problems I use the package wrapper `got-cjs`

**Comment by kbzowski** [comment] 2023-09-18 09:48
> To avoid problems I use the package wrapper `got-cjs`

But got-cjs is not updated. It is still 12.
Dynamic import and `type GotModule = typeof import('got');` worked fine with got 12, stopped with 13.

**Comment by bodrovis** [comment] 2023-09-23 13:00
Unfortunately certain customers that are using my SDK (that relies on Got) are also experiencing the same problem and it becomes a bit of a problem as it's not feasible for them to try all the solutions listed in this thread. I decided to give the Fetch API a go instead and it seems to do the trick

**Comment by rdzidziguri** [comment] 2023-10-30 11:01
The package's author does not care much about making the changes needed to make it work again. :slightly_smiling_face: I am. We ended up getting blocked from upgrading. Now, the team suggests dropping the package in favor of other competitors as we have 500+ consumers (businesses), and nobody can upgrade, as the changes mentioned here are not feasible. I am so sorry to leave the package, as we had some great experiences with it till V13 was released. You might be surprised, but some companies run SOC 2 audits as well, and we are forced to keep the package up to date so without having the option to make this backward compatible, we are going to switch to fat alternatives, unfortunately.

**Comment by micthiesen** [comment] 2023-10-31 19:50
Another workaround in case it's useful:

`tsconfig.json`
```
 "typeRoots": ["./node_modules/@types", "./types"]
```

`types/got-fix.d.ts`
```
declare module "got" {
  import got from "got/dist/source";
  export = got;
}
```

**Comment by rdzidziguri** [comment] 2023-11-01 13:33
If you want to make it work and you are on the latest TS 5.2.2, you can also set `moduleResolution` to `Bundler`; however, this makes you use the cutting-edge stack, which is not always the case, especially for large projects with a significant legacy.

**Comment by Denny966** [comment] 2023-11-14 18:05
I couldn't get any of the above solutions working with my setup so I created my own type file with some of the got API functions I use.

**It is by no means complete but it removes the warnings and it is strongly typed.**

```
declare module "got" {

    interface GotResponse {
        json<U>(): Promise<U>;
        text(): Promise<string>;
    }

    export function get(url: string, options: Options): GotResponse;
    export function post(url: string, options?: Options): GotResponse;

    export interface Options {
        headers?: Record<string, string>;
        method?: "GET"| "POST";
        timeout?: {
            request: number
        },
        responseType?: "json" | "buffer" | "text";
        url?: string;
        body?: any;
        json?: boolean;
    }
}
```

**Comment by pho3nixf1re** [comment] 2023-11-15 15:21
I extended @micthiesen 's solution to be a bit more direct. You shouldn't need to add it to `typeRoots` unless you have some kind of odd setup as `.d.ts` files will normally work out of the box within the project but... YMMV.

File: `/types/got.d.ts`

```
declare module 'got' {
  export * from 'got/dist/source/index.ts';
}
```

**Comment by monolithed** [comment] 2023-11-19 14:50
The method that works in Next.js@13:

**Comment by monolithed** [comment] 2023-11-19 14:53
Here's a workaround for Next.js@13:

```typescript
declare module 'got' {
    import * as got from 'got/dist/source';
    export = got;
}
```

I don't get the author's intention. Hundreds of people have spent time searching for and fixing a problem that may not have existed.

**Comment by kilianc** [comment] 2023-11-21 03:39
> I extended @micthiesen 's solution to be a bit more direct. You shouldn't need to add it to `typeRoots` unless you have some kind of odd setup as `.d.ts` files will normally work out of the box within the project but... YMMV. Note, this is for a distributed CLI tool and not Next.js. I am unsure how this would work with Next.
> 
> File: `/types/got.d.ts`
> 
> ```
> declare module 'got' {
>   export * from 'got/dist/source/index.ts';
> }
> ```

``` error TS2339: Property 'post' does not exist on type 'typeof import("got")'.```

sadly I get this, this is not worth the trouble I'll just use one of the other alternatives, which is the beauty of the js ecosystem!

**Comment by stewones** [comment] 2023-11-27 18:59
people want to push ESM hard but not everyone can afford the switch. libraries should provide commonjs modules as an alternative but the maintainers just don't care 🥲

**Comment by sindresorhus** [comment] 2023-11-29 19:55
All the problems mentioned here are caused by Next.js, Jest, TypeScript, and incorrect tsconfig, not Got. I understand it's easier to blame all the problems in the world on Got rather than your favorite tooling, but it's also not productive.

I have provided a straight forward [guide on how to use TypeScript with ESM](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-make-my-typescript-project-output-esm) that works. If you don't want to move to ESM, that's fine. You can continue to use an older version that is already stable. The ecosystem cannot stand still just because some users refuse to move on.

TypeScript had years to prepare for ESM, but they did not. Same with Jest. ESM was developed in the open and anyone could participate, including the TypeScript team. It had been in development for 10 years. Node.js released initial ESM support in [Node.js 12.17](https://nodejs.org/en/blog/release/v12.17.0) in May 2020, 2 years later (!), TypeScript finally [added support for ESM](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#esm-nodejs). ESM has been available for almost 3 years now.

**Closed by sindresorhus** 2023-11-29 19:55 UTC
