### ISSUE TITLE
Crashes if agent-base module is installed

### ISSUE THREAD

**Issue by benoitvidis** [sindresorhus/got#982] opened 2019-12-10 16:56 UTC
#### Describe the bug

 - Node.js version: 10+
 - OS & version: Ubuntu 18.04.01

When using got v10+ while the `agent-base` module is used (notably required by google sdk via teeny-request), got crashes with a `Cannot read property 'startsWith' of undefined`, i.e.:

```
"exception":{"name":"RequestError","stacktrace":["GotError: Cannot read property 'startsWith' of undefined","    at get (/opt/app/node_modules/got/dist/source/request-as-event-emitter.js:201:27)","    at urlToOptions (internal/url.js:1259:28)","    at Object.request (https.js:279:15)","    at Object.request (/opt/app/node_modules/agent-base/patch-core.js:27:22)"
```

The bug is actually induced by `agent-base` (cf https://github.com/TooTallNate/node-agent-base/issues/38) but could be worked-around in got by by passing the result of `url.parse` rather than an plain `url.URL` instance to the requestHandler.

#### Code to reproduce

```js
require('agent-base');
const got = require('got');

got('https://www.google.com').then(console.log);
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment] 2019-12-10 18:26
Duplicate of #968

**Closed by szmarczak** 2019-12-10 18:26 UTC
