### ISSUE TITLE
`ReadError: premature close` on DELETE requests after upgrading to 10.2.1 (from 9.6.0)

### ISSUE THREAD

**Issue by rlr** [sindresorhus/got#1014] opened 2020-01-06 20:37 UTC
#### Describe the bug

This is basically the same bug as filed in #990 that was supposed to be fixed.

We updated from 9.6.0 to 10.2.1 and as soon as it was deployed, we started getting `ReadError: premature close` all of our `DELETE` requests. The `GET` and `POST` requests work fine.

 - Node.js version: v12.13.1

#### Actual behavior

```
ReadError: premature close
  File "/home/node/guardian-website/node_modules/got/dist/source/as-promise.js", line 48, col 27, in EventEmitter.<anonymous>
    emitError(new errors_1.ReadError(error, options));
  File "internal/process/task_queues.js", line 93, col 5, in processTicksAndRejections
  File "/home/node/guardian-website/node_modules/end-of-stream/index.js", line 53, col 86, in onclosenexttick
    if (readable && !(rs && (rs.ended && !rs.destroyed))) return callback.call(stream, new Error('premature close'));
  File "internal/process/task_queues.js", line 75, col 11, in processTicksAndRejections
```

#### Expected behavior

We shouldn't get a `Premature close` error on successful `DELETE` requests.

#### Code to reproduce

```js
  const url = "https://example.com";
  const username = "username";
  const password = "password";
  const body = undefined;

  const resp = await got(url, {
    username,
    password,
    method: "DELETE",
    throwHttpErrors: false,
    responseType: "json",
    json: body ? body : undefined,
  });
```

#### Checklist

- [X] I have read the documentation.
- [X] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment] 2020-01-06 23:51
It **has** been fixed. There is a bug in Node.js v13.5.0 core but it's fixed too (no new release yet).

This part is interesting:
```js
File "/home/node/guardian-website/node_modules/end-of-stream/index.js", line 53, col 86, in onclosenexttick
```

Since Got doesn't require `end-of-stream`. It looks like a polyfill I think.

Unfortunately I cannot help you without a fully reproducible code.

**Comment by szmarczak** [comment] 2020-01-07 00:02
I think this is a duplicate of #981

**Closed** 2020-01-19 00:17 UTC
