### ISSUE TITLE
Basic auth doesn't work

### ISSUE THREAD

**Issue by epicfaace** [sindresorhus/got#1383] opened 2020-07-30 18:08 UTC
Strangely, this doesn't work (gives me back a 403):

```js
const auth = { username: "...", password: "..."};
const { results } = await got(CENSYS_IPV4_ENDPOINT, { ...auth }).json();
```

But using this request does work:
```js
    const { results } = await got(CENSYS_IPV4_ENDPOINT, {
      headers: {
        Authorization:
          'Basic ' +
          Buffer.from(`${auth.username}:${auth.password}`).toString('base64')
      }
    }).json();
```

Am I perhaps using the basic auth functionality of `got` incorrectly in the first example?

**Comment by szmarczak** [comment] 2020-07-30 19:56
Duplicate of #1169

**Closed by szmarczak** 2020-07-30 19:56 UTC
