### ISSUE TITLE
Dependency `cacheable-request` is outdated and does not distinguish POST requests with different bodies

### ISSUE THREAD

**Issue by AlCalzone** [sindresorhus/got#2138] opened 2022-09-09 12:09 UTC
#### Describe the bug

 - Node.js version: not relevant
 - OS & version: not relevant

Before version 8, `cacheable-request` does not correctly distinguish POST requests to the same URL if their body is different. This was fixed in https://github.com/jaredwray/cacheable-request/pull/31

I tried my hand at upgrading it, but due to changes to types that are used in got, this wasn't trivial for me. I'm sure someone who's more familiar with this codebase can do it in no time.

#### Actual behavior

`cacheable-request` is on version 7

#### Expected behavior

`cacheable-request` should be version 8 or 9

#### Code to reproduce

Not relevant, this is related to upgrading a dependency

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by jeswr** [comment] 2022-09-14 01:49
In addition `@types/cacheable-request` should be removed from version 9+ (see https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/62099). I've had some type errors occurring downstream that were caused by the presence of this type dependency in my node modules.

**Comment by jaredwray** [comment] 2022-09-15 18:46
This is being reviewed and looked at here: #2146 and tracked here: https://github.com/sindresorhus/got/issues/2129

Please follow along on those.

**Comment by nbouvrette** [comment] 2022-09-15 22:34
I just started having very odd issues related to `cacheable-request`. I'm still trying what triggered them, but `got` is the only dependency when I check with `npm list`. As per https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/62099, this can be fixed by both upgrading and removing the types:

```ts

node_modules/@types/cacheable-request/index.d.ts:26:42 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

26         cb?: (response: ServerResponse | ResponseLike) => void
                                            ~~~~~~~~~~~~

node_modules/@types/cacheable-request/index.d.ts:77:51 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

77             listener: (response: ServerResponse | ResponseLike) => void
                                                     ~~~~~~~~~~~~

node_modules/@types/cacheable-request/index.d.ts:81:69 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

81         on(event: 'response', listener: (response: ServerResponse | ResponseLike) => void): this;
                                                                       ~~~~~~~~~~~~

node_modules/@types/cacheable-request/index.d.ts:84:71 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

84         once(event: 'response', listener: (response: ServerResponse | ResponseLike) => void): this;
                                                                         ~~~~~~~~~~~~

node_modules/@types/cacheable-request/index.d.ts:89:51 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

89             listener: (response: ServerResponse | ResponseLike) => void
                                                     ~~~~~~~~~~~~

node_modules/@types/cacheable-request/index.d.ts:95:51 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

95             listener: (response: ServerResponse | ResponseLike) => void
                                                     ~~~~~~~~~~~~

node_modules/@types/cacheable-request/index.d.ts:104:51 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

104             listener: (response: ServerResponse | ResponseLike) => void
                                                      ~~~~~~~~~~~~

node_modules/@types/cacheable-request/index.d.ts:108:70 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

108         off(event: 'response', listener: (response: ServerResponse | ResponseLike) => void): this;
                                                                         ~~~~~~~~~~~~

node_modules/@types/cacheable-request/index.d.ts:112:73 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

112         listeners(event: 'response'): Array<(response: ServerResponse | ResponseLike) => void>;
                                                                            ~~~~~~~~~~~~

node_modules/@types/cacheable-request/index.d.ts:115:76 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

115         rawListeners(event: 'response'): Array<(response: ServerResponse | ResponseLike) => void>;
                                                                               ~~~~~~~~~~~~

node_modules/@types/cacheable-request/index.d.ts:118:60 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

118         emit(event: 'response', response: ServerResponse | ResponseLike): boolean;
```

**Comment by jaredwray** [comment] 2022-09-15 22:40
@nbouvrette - please see the plan above.

**Comment by nbouvrette** [comment] 2022-09-15 22:58
@jaredwray Yes I've been reading several threads but for some reason, no workaround is working so far.

**Comment by jaredwray** [comment] 2022-09-16 12:34
@nbouvrette - that is correct that there are no work arounds that I have seen so far. the goal is to update `cacheable-request` to latest in `got` which is in this pull request being worked on👇
 
https://github.com/sindresorhus/got/pull/2146

**Comment by jaredwray** [comment] 2022-09-16 12:43
Update to `cacheable-request` with the function requested change is now published: https://github.com/jaredwray/cacheable-request/releases/tag/v10.1.2

```diff
- const cacheableRequest = new CacheableRequest(https.request).createCacheableRequest();
+ const cacheableRequest = new CacheableRequest(https.request).request(); 
```

**Comment by nbouvrette** [comment] 2022-09-16 13:45
@jaredwray if I am following, there `got` still needs to publish a new release using the latest `cacheable-request` in order to fix the issue?

**Comment by jaredwray** [comment] 2022-09-16 13:58
> @jaredwray if I am following, there `got` still needs to publish a new release using the latest `cacheable-request` in order to fix the issue?

Correct. It is being actively worked on

**Comment by nbouvrette** [comment] 2022-09-16 14:03
For those interested I did find a workaround (required Node v+16):

Update your `package.json` and add:

```json
  "overrides": {
    "@types/cacheable-request": "8.3.1"
  },
```

Edit `/node_modules/cacheable-request/dist/types.d.ts` and remove the 4 first lines `/// <reference types="node" resolution-mode="require"/>` (they are triggering a `'resolution-mode' assertions are only supported when 'moduleResolution' is 'node16' or 'nodenext'.` error and I could not find anything on Google... removing them worked for me)

**Comment by sindresorhus** [comment] 2022-09-19 04:46
`cacheable-request` was updated in https://github.com/sindresorhus/got/releases/tag/v12.5.0

**Closed by sindresorhus** 2022-09-19 04:46 UTC

**Comment by AlCalzone** [comment] 2022-09-20 09:02
Unfortunately, this is only half-fixed. `got` does not pass the request body to `cacheable-request`. I'll raise a PR

**Comment by jaredwray** [comment] 2022-09-20 15:19
@AlCalzone - thanks for jumping on this.
