### ISSUE TITLE
default searchParams not properly merged when requesting searchParams is undefined

### ISSUE THREAD

**Issue by asomethings** [sindresorhus/got#1610] opened 2021-02-16 14:43 UTC
#### Describe the bug

 - Node.js version: 14.15.3
 - OS & version: Ubuntu 20.04.1 LTS

#### Actual behavior

Does not merge `searchParams` when `searchParams: undefined` making a request.
But, sends default `searchParams` when 
- searchParams does not exist in request options
- searchParams is an empty object in request options
- searchParams is an empty array in request options

```typescript
import got from 'got'

const gotExtended = got.extend({ searchParams: { query: true }, responseType: 'json' })
gotExtended('http://httpbin.org/get', { searchParams: undefined })
  .then((response) => response.body)
  .then(console.log)

/** Above returns
{
  args: {},
  headers: {
    Accept: 'application/json',
    'Accept-Encoding': 'gzip, deflate, br',
    Host: 'httpbin.org',
    'User-Agent': 'got (https://github.com/sindresorhus/got)',
    'X-Amzn-Trace-Id': 'Root=1-602bd8d5-5623f1de6a109692250b3177'
  },
  origin: 'xxx.xxx.xx.xxx',
  url: 'http://httpbin.org/get'
}
*/
```

#### Expected behavior

Should pass default `searchParams` even though requested `searchParams` is undefined

```typescript
import got from 'got'

const gotExtended = got.extend({ searchParams: { query: true }, responseType: 'json' })
gotExtended('http://httpbin.org/get', { searchParams: undefined })
  .then((response) => response.body)
  .then(console.log)

/** Above should return
{
  args: { query: 'true' },
  headers: {
    Accept: 'application/json',
    'Accept-Encoding': 'gzip, deflate, br',
    Host: 'httpbin.org',
    'User-Agent': 'got (https://github.com/sindresorhus/got)',
    'X-Amzn-Trace-Id': 'Root=1-602bd8d5-5623f1de6a109692250b3177'
  },
  origin: 'xxx.xxx.xx.xxx',
  url: 'http://httpbin.org/get?query=true'
}
*/
```

#### Code to reproduce

```typescript
import got from 'got'

const gotExtended = got.extend({ searchParams: { query: true }, responseType: 'json' })
gotExtended('http://httpbin.org/get', { searchParams: undefined })
  .then((response) => response.body)
  .then(console.log)
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment] 2021-02-26 08:27
Would you be able to submit a pull request with one or more [failing tests](https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md#failing-tests)? That would help to get this fixed faster.

**Comment by asomethings** [comment] 2021-03-26 18:51
@sindresorhus Sorry for the late reply. I just found out that it seems to be working as intended referring to [normalize-arguments.ts](https://github.com/sindresorhus/got/blob/main/test/normalize-arguments.ts#L40) test. It seems the test intends to reset the searchParams by putting `undefined` value in it. 
Can you confirm if it's intended behaviour?

**Comment by szmarczak** [comment] 2021-04-11 15:46
@asomethings It could be intended behavior, but I still don't like it as it's ambiguous. Anyway #1667 (merged, yay!) is much more stricter when providing options. In order to retain the previous options, simply omit them (or, if defined, use the `delete` operator).

Currently, only these options accept `undefined`: `searchParams`, `cookieJar` and `responseType`.

The following will reset those values:
- `instance(..., {searchParams: undefined}})`
- `instance(..., {cookieJar: undefined}})`
- `instance(..., {responseType: undefined}})`
- `instance(..., {prefixUrl: ''})`
- `instance(..., {agent: {http: undefined, https: undefined, http2: undefined}})`
- `instance(..., {context: {token: undefined, ...}})`
- `instance(..., {httpsOptions: {rejectUnauthorized: undefined, ...}})`
- `instance(..., {cacheOptions: {immutableMinTimeToLive: undefined, ...}})`
- `instance(..., {headers: {'user-agent': undefined, ...}})`
- `instance(..., {timeout: {request: undefined, ...}})`

In order to reset other options such as `retry` and `pagination`:
- `instance(..., {retry: got.defaults.options.retry})`
- `instance(..., {pagination: got.defaults.options.pagination})`

Note that `instance(..., {hooks: got.defaults.options.hooks})` has no effect. There are two ways to reset `hooks`:
```js
const createEmptyHooks = () => {
	return {
		    init: [],
		    beforeRequest: [],
		    beforeError: [],
		    beforeRedirect: [],
		    beforeRetry: [],
		    afterResponse: []
	};
};

// 1.
const secondInstance = instance.extend({mutableDefaults: true});
secondInstance.defaults.options.hooks = emptyHooks;

await secondInstance(...);

// 2.
await instance(..., {
	hooks: {
		init: [
			  (options, self) => {
				  self.hooks = createEmptyHooks();
			  }
		]
	}
});
```

We could implement `instance(..., {hooks: undefined})`, but you may ask how to reset particular hooks? Well, you need to use the above. So `hooks` doesn't accept `undefined` in order to be more transparent.

**Closed by szmarczak** 2021-04-11 15:46 UTC
Labels: bug, ✭ help wanted ✭

**Comment by szmarczak** [comment] 2021-04-11 15:48
Note that the above comment refers to the upcoming version of Got (12).
