### ISSUE TITLE
Get an empty body or zero length rawBody in some case

### ISSUE THREAD

**Issue by fengkx** [sindresorhus/got#1251] opened 2020-05-12 03:28 UTC
#### Describe the bug

 - Node.js version: Nodejs.14.1 & Nodejs.12.16.3
 - OS & version: Linux 5.5.19-1-MANJARO

#### Actual behavior
Get an empty body or zero length body

#### Expected behavior
Get the actual body

#### Code to reproduce
https://runkit.com/embed/tyzrkbthl3bs

#### Checklist

- [x] I have tried my code with the latest version of Node.js and Got.
- [x] I have read the documentation.

**Comment by Giotino** [comment] 2020-05-12 07:58
Related to #1234

Got 11 transform `http://www.newsmth.net/rss.php?mPicture` into `http://www.newsmth.net/rss.php?mPicture=` which body is empty

**Comment by Giotino** [comment] 2020-05-12 08:02
As suggested by @cookch10 here's a workaround

```
const url = new URL('http://www.newsmth.net/rss.php?mPicture');
const _search = url.search;
Object.defineProperty(url, 'search', {
  get() {
    return _search;
  },
  set() {
  }
});

;(async () => {
    const resp = await got.get(url);
    console.log(resp);
})()
```

**Comment by szmarczak** [comment] 2020-05-12 17:46
Duplicate of #1234

**Closed by szmarczak** 2020-05-12 17:46 UTC
