### ISSUE TITLE
got(...).json is not a function

### ISSUE THREAD

**Issue by borovik96** [sindresorhus/got#869] opened 2019-09-09 13:39 UTC
#### Describe the bug

 - Node.js version: v10.16.0
 - OS & version: MacOS 10.14.6 

#### Actual behavior

`got(...).json is not a function`

#### Expected behavior
The returned promise from `got` function has `.json` method

#### Code to reproduce
https://codesandbox.io/embed/distracted-glitter-duejq

```js
async function main() {
	await got(`https://test.com`).json(); 
}

main()
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment] 2019-09-09 13:40
Duplicate of #862

**Closed by sindresorhus** 2019-09-09 13:40 UTC

**Comment by sindresorhus** [comment] 2019-09-17 09:34
We have an alpha version of v10 out now if you wanna help us test: https://github.com/sindresorhus/got/releases/tag/v10.0.0-alpha.1
