### ISSUE TITLE
got 12.4.1 dependency cacheable-request does not transpile

### ISSUE THREAD

**Issue by AaronSterlingGENEICD** [sindresorhus/got#2129] opened 2022-09-02 23:02 UTC
#### Describe the bug
Running TypeScript 4.8.2:
Many errors generated on build of form
node_modules/@types/cacheable-request/index.d.ts:118:60 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

`npm explain latest-version`
cacheable-request@7.0.2 dev
node_modules/cacheable-request
  cacheable-request@"^7.0.2" from got@12.4.1
  node_modules/got
    got@"^12.1.0" from package-json@8.1.0
    node_modules/package-json
      package-json@"^8.1.0" from latest-version@7.0.0
      node_modules/latest-version
        dev latest-version@"^7.0.0" from the root project   

Problem remediated with:
```
"overrides": {
    "latest-version": {
      "got": "12.3.1"
    }
  }
```
and installing with 
`npm ci`
if installing with yarn, use --frozen-lockfile as noted by proton-ab below.

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by proton-ab** [comment] 2022-09-03 16:26
This is caused by https://github.com/sindresorhus/responselike/releases/tag/v3.0.0 which is breaking for https://github.com/jaredwray/cacheable-request due to removal of `@types/responselike` and renaming of `ResponseLike` type to `Response`.

**Comment by h-unterp** [comment] 2022-09-03 17:01
Yep. Wasted an hour tracking this down. Hardcoded 

   ` "got": "12.3.0",`

**Comment by BendingBender** [comment] 2022-09-05 12:23
This is a known issue. See https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/62111.

**Comment by Rehan-05** [comment] 2022-09-06 07:33
Still facing error

**Comment by proton-ab** [comment] 2022-09-06 09:29
Recommendation for everyone to pin `@types/responselike` for now.
```json
  "resolutions": {
    "@types/responselike": "1.0.0"
  },
```

Unless using frozen lockfile, you **WILL** fetch stub `@types/responselike` 3.0.0 because thoughtfully folks at DefinitelyTyped decided for `@types/cacheable-request` to depend on `"@types/responselike": "*"`. This will break your application/package regardless of whether you updated `got` or not.

**Comment by BendingBender** [comment] 2022-09-06 09:41
This is currently a known problem with DT: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/62111. You can workaround it by explicitly installing the older versions of the types packages:
```sh
npm i -D @types/cacheable-request@6.0.2 @types/responselike@1.0.0
```

Currently, the only way to really provide a fix is for this package to explicitly depend on `@types/responselike@1.0.0` or to upgrade the `responselike` dependendency to `cacheable-request@^8.3.1` or later.

**Comment by BendingBender** [comment] 2022-09-06 15:55
Antoher quick fix idea: include ambient types definitions from `@types/responselike@1.0.0` directly in this lib via a `.d.ts` file:
```ts
declare module 'responselike' {
  // copy-paste types from @types/responselike@1.0.0
}
```

**Comment by HansBrende** [comment] 2022-09-07 01:45
@BendingBender as of npm 8.3.0, I believe you can do the same thing with "overrides".

**Comment by BendingBender** [comment] 2022-09-08 20:36
Ok, the DTS maintainers now have moved the `latest` tag back to `@types/responselike@1.0.0`. Plz let me know if that fixes your problems.

**Comment by AaronSterlingGENEICD** [comment] 2022-09-08 20:44
Thank you @BendingBender . If someone in the thread builds successfully with the latest version of got, please post. We won't run a build with an affected library until early next week. If I'm the first to report, I'll close this thread when our build succeeds.

**Comment by proton-ab** [comment] 2022-09-09 19:39
This will never work, regardless of DTS fixing it. `got@12.4.1` depends on `"responselike": "^3.0.0"` but it also depends on `"cacheable-request": "^7.0.2",` which depends (and expects) `"responselike": "^2.0.0"`. Because `responselike@3.0.0` is breaking due to `ResponseLike => Respone` type rename.

Taking a deeper dive, for TS `cacheable-request@7.0.2` uses `"@types/cacheable-request": "^6.0.2"` which has following code:
```ts
import ResponseLike = require('responselike');
```
TypeScript compiler will hence look at `resposelike/index.d.ts` (ignoring `@types/responselike/index.d.ts` due to original package types taking precedence) and never find `ResponseLike` type there (as it is named `Response`).

Further, the only version of `responselike` installed by NPM/Yarn is `3.0.0` because `got` depends on it and `^2.0.0` of `cacheable-request` satisfies this requirement implicitly.

@sindresorhus You claim to support TS and ESM yet your own packages create a dependency conflict. Right now `got` in versions above `12.4.0` has dependency conflict (even if it isn't detected by package manager due to NPM versioning scheme deficiency). You have two options:
- Have `got` depend on `responselike@2.0.1`
- Create `responselike` version `4.0.0` and amend type name to be same as one provided by DTS (ie. `ResponseLike`).

@jaredwray
You were put in a bad situation and forced to bear some of result of `got` new release. Your choices are simple:
- Do nothing (there is no fault in `cacheable-request`
- Have `cacheable-request` depend on `responselike@3.0.0` (which should be simple and non-breaking you already depend on Node>=14)

**Comment by sindresorhus** [comment] 2022-09-10 05:43
> You claim to support TS and ESM yet your own packages create a dependency conflict. Right now got in versions above 12.4.0 has dependency conflict.

ESM works fine. This is a problem with TS.

> even if it isn't detected by package manager due to NPM versioning scheme deficiency

npm works how it has always worked. This is a TS deficiency.

**Comment by sindresorhus** [comment] 2022-09-10 06:13
I plan to upgrade `cacheable-request`, which will fix problem, but they need to make a new release first.

**Comment by AaronSterlingGENEICD** [comment] 2022-09-10 14:43
@sindresorhus Since you're in this thread, I'll take the opportunity to say: I really appreciate everything you've done for the community. A pleasure to interact at last.

**Comment by jaredwray** [comment] 2022-09-10 17:19
@sindresorhus  thanks for all the help on this and we have published `v10.0.0` of cacheable-request. Please let me know if you have any issues with it as there are some breaking changes. 

Release Notes for v9: https://github.com/jaredwray/cacheable-request/releases/tag/v9.0.0
Release Notes for v10: https://github.com/jaredwray/cacheable-request/releases/tag/v10.0.0

**Comment by proton-ab** [comment] 2022-09-10 20:45
> npm works how it has always worked. This is a TS deficiency.

Sorry I have forgot that conflicts with transitive dependencies are properly resolved here. I'll amend my original comment.

**Comment by sindresorhus** [comment] 2022-09-11 06:33
> Release Notes for v10: https://github.com/jaredwray/cacheable-request/releases/tag/v10.0.0

@jaredwray It would be great if the changelog included what it looked like before, not just the new way to call it. Right now it's very hard to see what needs changing. Example: https://github.com/sindresorhus/got/releases/tag/v12.0.0-beta.1 (see the examples with the diff syntax).

**Comment by sindresorhus** [comment] 2022-09-11 06:35
I probably won't be able to get to this for a couple of weeks. I'm traveling and have limited time, and I thought this would be a simple upgrade, but it doesn't seem so.

Pull request welcome if anyone wants it to happen sooner. Need to change stuff around: https://github.com/sindresorhus/got/blob/f0ac0b3fdfa82f53edfdc821ae3afa398b1bab0a/source/core/index.ts#L971-L1015

**Comment by sindresorhus** [comment] 2022-09-11 07:00
@jaredwray Also, `cacheable-request` has no code in the package when installed.

**Comment by jaredwray** [comment] 2022-09-11 20:01
> > Release Notes for v10: https://github.com/jaredwray/cacheable-request/releases/tag/v10.0.0
> 
> @jaredwray It would be great if the changelog included what it looked like before, not just the new way to call it. Right now it's very hard to see what needs changing. Example: https://github.com/sindresorhus/got/releases/tag/v12.0.0-beta.1 (see the examples with the diff syntax).

This has been updated with a diff and we will look at how to help on this with a pull request.

**Comment by jaredwray** [comment] 2022-09-11 20:06
> @jaredwray Also, `cacheable-request` has no code in the package when installed.

`cacheable-request` version 10.0.1 is now released with code in the package. Sorry for the issue on that. This also contains some minor updates to `keyv`, `normalize-url`, and a couple others. 

https://github.com/jaredwray/cacheable-request/releases/tag/v10.0.1

**Closed** 2022-09-19 04:37 UTC

**Comment by alexkvak** [comment] 2022-10-19 14:28
@sindresorhus have you plan to port this fix to got@11?

**Comment by sindresorhus** [comment] 2022-10-19 15:39
> have you plan to port this fix to got@11?

No
