### ISSUE TITLE
transpilation errors raised due to got in typescript

### ISSUE THREAD

**Issue by luichooy** [sindresorhus/got#2137] opened 2022-09-09 10:11 UTC
#### Describe the bug

 - Node.js version: 14.16.1
 - OS & version: MacOS
 - typescript: 4.3.5 & 4.8.2 & 3.x.x
 - got: 12.4.1

#### Actual behavior

I installed got@12 as devDependencies for benchmark test and not use in source directory (src)
I guess some tools use it when i run `npm run build`

when i use typescript to compile the project,  transpilation errors raised due to got. Errors are as follow:

```
node_modules/got/dist/source/core/index.d.ts:15:24 - error TS1005: ',' expected.

15 import Options, { type NativeRequestOptions } from './options.js';
                          ~~~~~~~~~~~~~~~~~~~~

node_modules/got/dist/source/core/index.d.ts:16:15 - error TS1005: ',' expected.

16 import { type PlainResponse, type Response } from './response.js';
                 ~~~~~~~~~~~~~

node_modules/got/dist/source/core/index.d.ts:16:35 - error TS1005: ',' expected.

16 import { type PlainResponse, type Response } from './response.js';
                                     ~~~~~~~~

node_modules/got/dist/source/core/options.d.ts:21:29 - error TS1005: ',' expected.

21 import http2wrapper, { type ClientHttp2Session } from 'http2-wrapper';
```

I solved it by downgrading Got to 11.x.x. Because version 11.x.x has no `import type `syntax.

#### Expected behavior

I'm confused about whether this is a got problem or a typescript problem

#### Code to reproduce

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es5",
    "outDir": "./lib",
    "skipLibCheck": true
  },
  "include": ["src/**/*", "./types/*.d.ts"],
}
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by proton-ab** [comment] 2022-09-09 19:50
Duplicate of https://github.com/sindresorhus/got/issues/2129

**Closed** 2022-09-12 15:35 UTC
