### ISSUE TITLE
The `authorization` header is improperly encoded

### ISSUE THREAD

**Issue by bruno-xo7** [sindresorhus/got#1169] opened 2020-04-21 09:32 UTC
#### Actual behavior

When I use the username/password with got, It seems that the combo 'username:password' is encoded with encodeURI() before to be encode in base64 for the basic auth. This first encoding is not necessary due to the base64 encoding and brings problems. So when the encodeURI() change a value like '@' to '%40', the basic authentification doesn't work.

#### Expected behavior

Just encode the combo 'username:password' with base64 encoding.

#### Code to reproduce

```js
const got = require('got');

(async () => {
  const response = await got.head("http://example.com/", {username: "user@", password: "password@"});
  console.info("Response:", response.client._httpMessage._header);
}) ();
```
We see that the Authorization header is invalid

#### Checklist

- [X] I have read the documentation.
- [X] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment] 2020-04-21 19:14
It's a Node.js issue:

```js
const https = require('https');
const getStream = require('get-stream');

const url = new URL('https://httpbin.org/anything');
url.username = 'user@';
url.password = 'password';

https.get(url, async response => {
    const body = await getStream(response);
    console.log(JSON.parse(body));
});
```

I'm not sure whether it's a bug or valid behavior...

**Comment by szmarczak** [comment] 2020-04-21 19:17
Reference: https://tools.ietf.org/html/rfc2617 (haven't looked at it yet)

**Comment by szmarczak** [comment] 2020-04-21 19:19
Took a quick look and found this:

```
      user-pass   = userid ":" password
      userid      = *<TEXT excluding ":">
      password    = *TEXT
```

**Comment by szmarczak** [comment] 2020-04-21 19:25
https://github.com/nodejs/node/issues/31439

**Comment by bruno-xo7** [comment] 2020-04-22 07:34
also [nodejs/node#31450](https://github.com/nodejs/node/pull/31450)

The both issues are still open in Nodejs.

I did this workaround on my side until Nodejs fixes the issue:
```js
  const headers = {
    "Authorization": "Basic " + Buffer.from(`user@:password@`).toString("base64")
  };
  await got(encodeURI("http://example.com/"), { headers });
```
I built the Authorization header instead of filling username and password members of the options objects.

If Nodejs only fixes it on the new version, maybe Got can fix the issue on their side to avoid the bug on old Nodejs versions.

**Comment by szmarczak** [comment] 2020-04-22 07:40
> maybe Got can fix the issue on their side

We could implement a workaround, but it's not the proper solution. The bug is not a big one, so I'd rather wait until it's fixed on Node.js side.

**Comment by kamikazechaser** [comment] 2020-12-12 16:30
@szmarczak Let the library encode it properly, internally. I feel this is a major issue since the library has the `options.username` and `options.password` option.

**Comment by andyburke** [comment] 2021-07-17 04:34
Got caught by this. Feeling agreement with @kamikazechaser: got could essentially make this work correctly by handling the username/password itself.

**Comment by legopin** [comment] 2021-07-19 03:33
At the very least there should be documentation linking to this issue, took me a while to suspect what went wrong
https://github.com/sindresorhus/got/blob/main/documentation/2-options.md#username

**Comment by szmarczak** [comment] 2021-08-02 07:27
Let's fix this. I don't think Node.js will fix this anytime soon, given how much time we have already waited. Furthermore, both Google Chrome and Firefox don't support (which is weird) `username` and `password` in URL in `fetch`.

**Comment by szmarczak** [comment] 2021-08-02 07:34
Actually we just have to wait for a Node.js release: https://github.com/nodejs/node/pull/39310 :tada:

**Comment by szmarczak** [comment] 2021-08-04 06:22
I'll fix this later today in Got :)

**Closed** 2021-08-04 21:23 UTC
Labels: bug, external, nodejs bug

**Comment by AbdelrahmanHafez** [comment] 2021-08-22 17:31
@szmarczak
Would a PR to merge this fix into v11 be welcome?
I just spent 3 hours trying to fix issues caused by this bug and I would love to prevent other people from having the same issue.

**Comment by Joe-Palmer** [comment] 2021-08-22 22:46
I would very much welcome this fix in v11
