### ISSUE TITLE
Extend/typing regression in v11

### ISSUE THREAD

**Issue by pasieronen** [sindresorhus/got#1178] opened 2020-04-23 11:38 UTC
#### Describe the bug

 - Node.js version: 12.16.2
 - OS & version: MacOS 10.15.4 
 - Typescript version: 3.8.3

#### Actual behavior

With got 11.0.2, this file results in TypeScript compiler error:

```js
import got from 'got'

interface ServerResponse { foo: number }

const jsonClient = got.extend({ responseType: 'json' });

jsonClient.post<ServerResponse>('http://localhost:3030/', { json: { bar: 1 } }).then(r => console.log(r.body.foo))
```

The error is:

```
test.ts:7:59 - error TS2769: No overload matches this call.
  Overload 1 of 16, '(url: string | URL, options?: Merge<Options, { isStream?: false; resolveBodyOnly?: false; responseType: "json"; }>): CancelableRequest<Response<ServerResponse>>', gave the following error.
    Argument of type '{ json: { bar: number; }; }' is not assignable to parameter of type 'Merge<Options, { isStream?: false; resolveBodyOnly?: false; responseType: "json"; }>'.
      Property 'responseType' is missing in type '{ json: { bar: number; }; }' but required in type '{ isStream?: false; resolveBodyOnly?: false; responseType: "json"; }'.
  Overload 2 of 16, '(url: string | URL, options?: Merge<Merge<Options, { isStream?: false; resolveBodyOnly?: false; responseType: "json"; }>, ResponseBodyOnly>): CancelableRequest<...>', gave the following error.
    Argument of type '{ json: { bar: number; }; }' is not assignable to parameter of type 'Merge<Merge<Options, { isStream?: false; resolveBodyOnly?: false; responseType: "json"; }>, ResponseBodyOnly>'.
      Property 'responseType' is missing in type '{ json: { bar: number; }; }' but required in type 'Pick<Merge<Options, { isStream?: false; resolveBodyOnly?: false; responseType: "json"; }>, "search" | "host" | "password" | "body" | "form" | "path" | "json" | "timeout" | ... 54 more ... | "sessionIdContext">'.

7 jsonClient.post<ServerResponse>('http://localhost:3030/', { json: { bar: 1 } }).then(r => console.log(r.body.foo))
                                                            ~~~~~~~~~~~~~~~~~~~~

  node_modules/got/dist/source/types.d.ts:28:5
    28     responseType: 'json';
           ~~~~~~~~~~~~
    'responseType' is declared here.
  node_modules/got/dist/source/types.d.ts:28:5
    28     responseType: 'json';
           ~~~~~~~~~~~~
    'responseType' is declared here.


Found 1 error.
```

#### Expected behavior

With got 10.7.0, the code compiles fine.

#### Code to reproduce

See above.

#### Checklist

- [X] I have read the documentation.
- [X] I have tried my code with the latest version of Node.js and Got.

**Comment by dscalzi** [comment] 2020-05-02 14:00
Can confirm issue persists on `v11.1.0`.

**Comment by szmarczak** [comment] 2020-05-02 14:14
I think this d3b972efaca28d8033468c7232a469e8cb034677 may be the culprit, but haven't tried your example yet.

**Comment by dscalzi** [comment] 2020-05-02 14:27
Here's a sample test that should work, yet fails with this regression (and should be added to the test suite).

```typescript
test('sends plain objects as JSON using extended client', withServer, async (t, server, got) => {
	server.post('/', defaultEndpoint);

	const extendedClient = got.extend({ responseType: 'json' })

	const {body} = await got.post<{such: 'wow'}>({
		json: {such: 'wow'}
	});
	t.deepEqual(body, {such: 'wow'});
});
```

I don't think the `<{such: 'wow'}>` would be needed when this is fixed.

**Comment by dscalzi** [comment] 2020-05-02 15:13
Just checked back to v10.7.0, this wasnt necessarily working as intended their either. It was using the `responseType?: 'default'` signature (defined here https://github.com/sindresorhus/got/blob/v10.7.0/source/create.ts#L49, removed in v11). In order for this to be properly implemented, there would have to be some kind of relationship between the InstanceDefaults and the options parameter of the GotRequestFunction.

**Comment by szmarczak** [comment] 2020-05-03 17:36
This is actually a duplicate of https://github.com/sindresorhus/got/issues/1117, closing.

**Comment by szmarczak** [comment] 2020-05-03 17:39
Actually this shouldn't error, sorry.

**Closed** 2020-05-03 17:53 UTC
Labels: bug, ✭ help wanted ✭
