### ISSUE TITLE
Do not use invalid cache

### ISSUE THREAD

**Issue by yovanoc** [sindresorhus/got#963] opened 2019-12-04 10:37 UTC
#### Describe the bug

 - Node.js version: 13.3
 - OS & version: MacOS Catalina

#### Actual behavior

I get `GotError: Unexpected token  in JSON at position 0 in ...` when I add `responseType: "json"` .
But this happens 2 times out of 5 .. and If I remove the responseType and log the body, all is good..

PS: right before this error there is this warning every time: `(node:34140) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

#### Expected behavior

Should be able to parse JSON, I think got tries to parse before getting full response or something like that

#### Code to reproduce

```js
const body = await got
    .get(link, {
      cache,
      retry: 4
    })
    .json();
```

or 

```js
const { body } = await got
    .get(link, {
      cache,
      retry: 4,
      responseType: 'json'
    });
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment] 2019-12-04 11:49
What's the link? If it's a custom server, please attach some code. What's the cache options?

**Comment by yovanoc** [comment] 2019-12-04 12:29
Can we exchange by email for links? It's a private project?

**Comment by szmarczak** [comment] 2019-12-04 12:53
That won't be neccessary I think. If you open the link in your browser, what's the first character?

> What's the cache options?

Also if you provided the full stack trace, that'd be awesome.

**Comment by yovanoc** [comment] 2019-12-04 13:01
The first character is the `{`.

Here's the cache:

```ts
const cache = new KeyvFile({
  filename: join(appDataPath, "cache.json"), // the file path to store the data
  expiredCheckDelay: 10 * 24 * 3600 * 1000, // ms, check and remove expired data in each ms
  writeDelay: 120, // ms, batch write to disk in a specific duration, enhance write performance.
  encode: JSON.stringify, // serialize function
  decode: JSON.parse // deserialize function
});
```

And I will try to provide you a bigger stacktrace, thanks

**Comment by szmarczak** [comment] 2019-12-04 13:04
Thanks, I'll now investigate.

**Comment by szmarczak** [comment] 2019-12-04 13:08
> right before this error there is this warning every time

This is actually weird as Got never does `Buffer(...)`. It does `Buffer.from(...)`...

**Comment by szmarczak** [comment] 2019-12-04 13:10
If you can provide HTTP headers, that'd awesome as well (you may leave out some of them if they are sensitive).

**Comment by yovanoc** [comment] 2019-12-04 13:13
Response headers? Because I don't pass any for the request

**Comment by szmarczak** [comment] 2019-12-04 13:15
yup

**Comment by yovanoc** [comment] 2019-12-04 13:19
```json
{
  'content-type': 'application/json',
  'last-modified': 'Wed, 27 Nov 2019 01:56:55 GMT',
  server: 'AmazonS3',
  'content-encoding': 'gzip',
  vary: 'Accept-Encoding',
  'x-cache': 'Hit from cloudfront',
  via: '1.1 3df1d6f6e1999cb29078ddff1a62bd1d.cloudfront.net (CloudFront)',
  'x-amz-cf-pop': 'FRA2-C1',
  'x-amz-cf-id': 'YCwpKGhFg9pHwZ3BNOPGPG33cTTp7mvg9w4eKTdSpmo4lthhz0hI9A==',
  age: '44979',
  date: 'Wed, 04 Dec 2019 13:19:11 GMT'
}
```

**Comment by yovanoc** [comment] 2019-12-05 13:00
@szmarczak  I've done more tests. If I simply remove the cache, all is working perfectly. AND I've tried to do a setInterval to request once a second the .json (with the cache) and 1/2 times the data is completely invalid (weird ascii characters) so I think now the cache must have an issue

**Comment by szmarczak** [comment] 2019-12-05 15:45
Could you provide the full error stacktrace?

**Comment by yovanoc** [comment] 2019-12-05 18:18
```
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at parseBody (/Users/devchris/Documents/code/nodejs/project/node_modules/got/dist/source/as-promise.js:12:47)
    at /Users/devchris/Documents/code/nodejs/project/node_modules/got/dist/source/as-promise.js:130:47
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

How can I get more? Isn't good for you?

**Comment by szmarczak** [comment] 2019-12-05 21:22
Unfortunately I cannot reproduce this one. If you want to you can email me here:

sz.marczak@gmail.com

I'll be more than happy to help.

**Comment by szmarczak** [comment] 2019-12-05 21:25
It seems that it's a zero-width space character: `JSON.parse('​')` gives the same result. Could you try `.text()` instead of `.json()` and log these bodies?

**Comment by yovanoc** [comment] 2019-12-05 21:37
Just sent to you an email, thanks

**Comment by szmarczak** [comment] 2019-12-05 22:57
Replied back

**Comment by szmarczak** [comment] 2019-12-08 14:28
Culprit: https://github.com/kornelski/http-cache-semantics/issues/26

**Comment by szmarczak** [comment] 2019-12-23 23:40
`http-cache-semantics` works properly. The second response doesn't include any validation header so headers shouldn't be merged.

Instead, it should make a new request or return the new response without merging anything.

I'll move this into #875

**Closed by szmarczak** 2019-12-23 23:40 UTC
Labels: bug, external
