### ISSUE TITLE
process exit without any reason

### ISSUE THREAD

**Issue by UchihaYuki** [sindresorhus/got#1948] opened 2021-12-11 11:57 UTC
#### Describe the bug

 - Node.js version: v16.2.0
 - OS & version: windows 10
 - got: 11.8.3

#### Actual behavior
The process exits without any error, after several loops (sometimes 3, sometimes 90, not certain)

#### Expected behavior
Run permanantly

#### Code to reproduce

```js
import got from "got";
import { HttpsProxyAgent } from "https-proxy-agent";

async function main() {
  let counter = 0;
  while (true) {
    const res = await got("https://ipapi.co/json/", {
      agent: {
        https: new HttpsProxyAgent(
          `https://${process.env.PS_PROXY_USERNAME}:${process.env.PS_PROXY_PASSWORD}@${process.env.PS_PROXY_HOST}:${process.env.PS_PROXY_PORT}`
        ),
      },
      headers: {
        "User-Agent":
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36",
      },
      responseType: "json",
      timeout: 5e3,
    });
    console.log(counter++, (res.body as any)?.region);
  }
}

main().catch((error) => console.log(error));
```

**Comment by sindresorhus** [comment] 2021-12-11 13:00
Try upgrading to the latest Node.js v16 release. If that doesn't solve the problem, try Got v12.

**Comment by UchihaYuki** [comment] 2021-12-12 02:30
> Try upgrading to the latest Node.js v16 release. If that doesn't solve the problem, try Got v12.

By upgrading to Node:v16.13.1 and got 12.0.0, I got the following error:
const got_1 = (0, tslib_1.__importDefault)(require("got"));
                                                                  ^
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\x\node_modules\got\dist\source\index.js from 
C:\x\ps-geo.js not supported.

**Comment by UchihaYuki** [comment] 2021-12-12 03:05
I upgraded to node: v16.13.1 and got: 12.0.0. The problem still exists.

**Comment by szmarczak** [comment] 2021-12-12 03:19
Can you try without proxy? If it works without proxy then it's rather a proxy issue.

**Comment by UchihaYuki** [comment] 2021-12-12 04:29
> Can you try without proxy? If it works without proxy then it's rather a proxy issue.

I didn't try it because of the rate limit on the API. But I just tried it out with another proxy package. It seems the problem does come from that package. Does `got` have a recommended packet on HTTPS proxy agent that just works. I tried `hpagent`, it still doesn't work. (Only works with HTTP proxy server).

**Comment by szmarczak** [comment] 2021-12-13 01:08
https://github.com/apify/got-scraping/blob/739358100a30d9c73cbb2214371943a8e133a694/src/agent/h1-proxy-agent.ts

**Comment by szmarczak** [comment] 2021-12-13 01:09
This looks like a duplicate of https://github.com/sindresorhus/got/issues/1393

**Closed** 2021-12-13 05:41 UTC
