### ISSUE TITLE
Invalid extra escape for URLs

### ISSUE THREAD

**Issue by Hamper** [sindresorhus/got#1180] opened 2020-04-23 21:48 UTC
#### Describe the bug

 - Node.js version: 12.16.2
 - OS & version: gentoo linux 

Invalid extra escape for urls only in got v11, not in v10

#### Actual behavior
Got escapes some symbols like `~` in url but should not do this because some servers don't parse such escaped symbols

#### Expected behavior
Symbols in URLs like `~` must not be escaped

#### Code to reproduce

```js
const got = require('got');
const testURL = 'https://example.com/?test=test~test';
console.log('RIGHT URL:\n%o\n', new URL(testURL));
(async ()=>{
    try{
        await got(testURL, {
            hooks: {
                beforeRequest: [
                    (options) => {
                        console.log('GOT URL:\n%o\n', options.url);
                    }
                ]
            }
        });
    }
    catch(e){
    }
})();
```
same result with `new URL(testURL))` in got parameters

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment] 2020-04-24 00:13
It's a bug in the Node.js implementation. Try using URLSearchParams. The URL is normalized according to the spec. If servers don't follow the spec then it's not our problem.

Duplicate of #1113

**Closed by szmarczak** 2020-04-24 00:13 UTC

**Comment by Hamper** [comment] 2020-04-24 06:37
According to https://tools.ietf.org/html/rfc3986#section-2.3 tilde is unreserved and *should not encoded* by URI producers.

querystring.escape() - does not escape tilde
new URL() - does not escape tilde
browsers - does not escape tilde, normalize %7E as ~ before sending
got 10 - does not escape tilde

got 11 *escapes* tilde but should not according to RFC

**Comment by szmarczak** [comment] 2020-04-24 07:25
Got doesn't do this. It's the native `URLSearchParams`. And, according to the WHATWG implementation the behavior is correct (see the original issue).  I'll open a Node.js issue.
