### ISSUE TITLE
Why GOT convert custom header name into Lower case ?

### ISSUE THREAD

**Issue by balaji-desai** [sindresorhus/got#1805] opened 2021-07-26 09:13 UTC
#### What would you like to discuss?

I am using below code:

   const gotOptions: Options = {
            allowGetBody: true,
            encoding: (responseEncoding || RESPONSE_ENCODING_UTF8) as BufferEncoding,
			headers: {},
            host: serviceUrl.hostname,
            method: httpMethod as Method,
            pathname: decodeURI(serviceUrl.path),
            protocol: serviceUrl.protocol,
            retry: 0,
            timeout: timeout,
        };
  gotOptions.headers["My-Custom-Header"] = "mycustomheader";
  await got(uri, gotOptions);

the service receives the header name as - my-custom-header

why it is converting header name into lower case ?
Is there any way to send header whiteout converting it into lower case ?
#### Checklist

- [x] I have read the documentation.

**Comment by sindresorhus** [comment] 2021-07-26 10:03
Duplicate of #1335

**Closed by sindresorhus** 2021-07-26 10:03 UTC
