### ISSUE TITLE
Argument of type 'URL' is not assignable to parameter of type 'Options'.

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/got#1247] opened 2020-05-11 19:10 UTC
#### Describe the bug

- Got version: 11.1.3
 - Node.js version: 12.16.3
 - OS & version: macOS 10.15.4

Using TypeScript and passing in a WHATWG `URL`, but the compiler is complaining.

#### Actual behavior
```
my-file.ts:85:26 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type 'URL' is not assignable to parameter of type 'Options'.
      Types of property 'searchParams' are incompatible.
        Type 'URLSearchParams' is not assignable to type 'string | URLSearchParams | { [key: string]: string | number | boolean | null; } | undefined'.
          Type 'URLSearchParams' is not assignable to type '{ [key: string]: string | number | boolean | null; }'.
            Index signature is missing in type 'URLSearchParams'.
```

#### Expected behavior
Happiness.

#### Code to reproduce

```ts
// TypeScript
got(new URL('https://google.com'));
```

#### Checklist

- [x] I have read the documentation.
- [ ] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment] 2020-05-11 21:41
Duplicate of #989

**Closed by szmarczak** 2020-05-11 21:41 UTC
