### ISSUE TITLE
Option types unnecessarily closed

### ISSUE THREAD

**Issue by phawxby** [sindresorhus/got#1060] opened 2020-02-11 14:34 UTC
#### What problem are you trying to solve?
I'm in the process of migrating from got 9 relying on `@types/got` to got 10 and it's native types. Within out codebase we have various little wrappers around got to help with various things, make code more easily testable, etc. The `@types/got` typings provided [`GotJSONOptions`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/got/index.d.ts#L193-L199), `GotFormOptions<string>`, etc. These are available in the native got typings but not exported.
https://github.com/sindresorhus/got/blob/1f363b976cd23626462314c7cd5670cddd951c73/source/create.ts#L38-L42

...

#### Describe the feature
Export the got options types. 

...

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by szmarczak** [comment] 2020-02-11 16:56
Duplicate of #954

**Closed by szmarczak** 2020-02-11 16:56 UTC
