### ISSUE TITLE
Cross-origin redirect with basic auth is incorrect

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/got#1652] opened 2021-03-03 19:50 UTC
#### Describe the bug
Basic authentication headers persist across redirects to different origins.

 - Got version: 10.0.2
 - Node.js version: 14.16.0
 - OS & version: macOS 10.15.7

#### Expected behavior
Basic authentication should not be transitive across redirects to a different origin.

#### Code to reproduce

```js
got.stream(url, {
  auth: 'user:pass',
  method: 'get'
})
  .on('redirect', ({ headers }) => console.log(headers))
```

#### Checklist

- [x] I have read the documentation.
- [ ] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment] 2021-03-04 22:41
There is no `auth` option in the docs.

**Comment by szmarczak** [comment] 2021-03-04 22:42
Please upgrade to `11.8.2` :)

**Comment by stevenvachon** [comment] 2021-03-04 23:49
It night be reproducible with v11.x and its `username`/`password` properties, but I can't yet upgrade due to some mysterious issues.

**Comment by szmarczak** [comment] 2021-03-05 02:11
Looks like a duplicate of #1090

**Comment by szmarczak** [comment] 2021-03-05 02:11
> mysterious issues

WDYM?

**Comment by stevenvachon** [comment] 2021-03-05 02:28
> Looks like a duplicate of #1090

Ah, so it's specifically fixed in v11? That would be most excellent!


> > mysterious issues
> 
> WDYM?

https://github.com/Woorank/robots-txt-parse/issues/7 -- it's closed, but only because that lib doesn't seem to be to blame.

**Comment by szmarczak** [comment] 2021-03-05 02:53
https://github.com/sindresorhus/got/issues/223#issuecomment-405076226

**Closed** 2021-03-21 03:24 UTC
