### ISSUE TITLE
Tries to import Electron

### ISSUE THREAD

**Issue by denizdogan** [sindresorhus/got#407] opened 2017-11-07 09:56 UTC
This might be because I'm using Webpack with Babel and Flow and what-not, but I can't use this library because of the Electron support. It seems to try to import Electron even though I don't have Electron in my environment and I pass `{useElectronNet: false}`.

    ERROR in ./node_modules/got/index.js
    Module not found: Error: Can't resolve 'electron' in '/Users/deniz/Code/editor/node_modules/got'
    @ ./node_modules/got/index.js 45:20-39
    @ ./src/actions/grid.js
    @ ./src/components/LoadingScreen.jsx
    @ ./src/components/App.jsx
    @ ./src/index.js
    @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch ./src/index.js

**Comment by sindresorhus** [comment] 2017-11-07 16:03
Duplicate of #345

**Closed by sindresorhus** 2017-11-07 16:03 UTC
