### ISSUE TITLE
Not possible to return instances of a custom Error class from the beforeError hook

### ISSUE THREAD

**Issue by p-bakker** [sindresorhus/got#1712] opened 2021-05-03 12:47 UTC
#### What would you like to discuss?
I'm in the process of porting over an existing SDK to internally use `got` and am trying to intercept (among others) instances of HTTPError and trying to get an instance of a custom error class thrown instead.

Am trying to do so via the beforeError hook, but it's not working: a RequestError gets thrown instead.

It seems that the destroy method (which is called after processing of the beforeError hooks) does a check if the error instance is an instanceof RequestError and if not, creates a new RequestError instance and throws that instead

The reason I'm attempting to replace the RequestError instances with custom error instances is to make sure our SDK remains backwards compatible with the existing implementation that is not based on `got` (and forwards compatible if we ever have the need to move away from `got` again)

Alternatively I'd have to put in a .catch() on every call to `got` in the SDK code and handle the conversion there, but I rather do that nice and cleanly, once, through hooks

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment] 2021-05-03 13:17
Have you browsed already open issues? There is already an issue exactly like this one on the very first page.

**Comment by szmarczak** [comment] 2021-05-03 13:17
Duplicate of #1353

**Closed** 2021-05-03 13:16 UTC

**Comment by szmarczak** [comment] 2021-05-03 13:18
If you have any idea on how this could be fixed, feel free to share the ideas in the issue above :)

**Comment by p-bakker** [comment] 2021-05-04 08:51
I had not seen the existing case, my apologies.

That case does seem a bit different though, as it seems to be about casting for TypeScript purposes, but I'll add my thoughts to is anyway
