### ISSUE TITLE
stream pipeline ends without an error, despite request timeout

### ISSUE THREAD

**Issue by AshenCoon** [sindresorhus/got#1290] opened 2020-05-26 18:49 UTC
#### Describe the bug

 - Node.js version: v12.16.1
 - OS & version: Ubuntu 18.04.4 LTS

#### Actual behavior
On request timeout stream "error" event occurrs after stream "end" event. This cause pipeline to end without an error

#### Expected behavior
error should be passed to pipeline callback

#### Code to reproduce

```js
const writeStream = fs.createWriteStream(path.resolve(__dirname, "test"));
const reqStream = got.stream(
  "<url that takes more than 1s to download>",
  {
    method: "get",
    timeout: 1000,
  }
);

reqStream.on("error", (err) => {
  console.log("reqStream.error", err.message);
});

stream.pipeline(reqStream, writeStream, (err) => {
  if (err) {
    console.log("pipeline.error", err.message);
  } else {
    console.log("pipeline.success");
  }
});
```
execution result:
```
pipeline.success
reqStream.error Timeout awaiting 'request' for 1000ms
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by Giotino** [comment] 2020-05-26 19:01
#1269

**Comment by AshenCoon** [comment] 2020-05-27 08:18
Not sure if that's the same issue. Error event emits after end without using pipeline. Though in the current stable node(v13.10.1) it seems to be fixed.

**Comment by szmarczak** [comment] 2020-05-27 14:55
Seems like a bug. Can you make a full reproducible example?

**Comment by AshenCoon** [comment] 2020-05-27 17:27
It really is like in the head post, except for require and real url.
the only package installed is got v11.1.4.

```js
const fs = require("fs");
const path = require("path");
const stream = require("stream");
const got = require("got");

const writeStream = fs.createWriteStream(path.resolve(__dirname, "test"));
const reqStream = got.stream("https://speed.hetzner.de/100MB.bin", {
  method: "get",
  timeout: 1000,
});

reqStream.on("error", (err) => {
  console.log("reqStream.error", err.message);
});

reqStream.on("end", () => {
  console.log("reqStream.end");
});

stream.pipeline(reqStream, writeStream, (err) => {
  if (err) {
    console.log("pipeline.error", err.message);
  } else {
    console.log("pipeline.success");
  }
});
```

the output is
```
reqStream.end
pipeline.success
reqStream.error Timeout awaiting 'request' for 1000ms
```

**Comment by szmarczak** [comment] 2020-05-27 21:56
It seems to be fixed on Node.js 12.16.3 https://runkit.com/szmarczak/5ecee0fbee18e80013e53258

**Comment by AshenCoon** [comment] 2020-05-28 08:43
Hm. I cloned your notebook and second time i ran it i got what i described
https://runkit.com/ashencoon/5ecf6eb4330279001b9a5de5
It seems like its not consistent.

**Comment by kirillgroshkov** [comment] 2020-06-09 10:14
We're facing this too!

**Comment by Giotino** [comment] 2020-06-09 12:26
I might have found the possible cause
`writable.end([chunk[, encoding]][, callback])`
The `callback` in Node.JS >= 14 is also used for the `finish` event and not only for the `error` event.

Node.JS 14: https://nodejs.org/api/stream.html#stream_writable_end_chunk_encoding_callback
Node.JS 12: https://nodejs.org/docs/latest-v12.x/api/stream.html#stream_writable_end_chunk_encoding_callback

**Comment by szmarczak** [comment] 2020-07-05 23:14
I cannot reproduce the bug on Node.js > 12.18.2.

**Comment by szmarczak** [comment] 2020-07-05 23:19
I can always reproduce this on Node.js 12.18.2:

```js
const fs = require("fs");
const path = require("path");
const stream = require("stream");
const got = require("got");

const writeStream = fs.createWriteStream(path.resolve(__dirname, "blah"));
const reqStream = got.stream("https://speed.hetzner.de/100MB.bin", {
  method: "get",
  timeout: 1000,
  hooks: {
	  beforeError: [
		  async error => {
			await new Promise(resolve => setTimeout(resolve, 1000));
			return error;
		  }
	  ]
  }
});

reqStream.on("error", (err) => {
  console.log("reqStream.error", err.message);
});

reqStream.on("end", () => {
  console.log("reqStream.end");
});

stream.pipeline(reqStream, writeStream, (err) => {
  if (err) {
    console.log("pipeline.error", err.message);
  } else {
    console.log("pipeline.success");
  }
});
```

seems to be fixed for newer Node.js versions.

**Closed** 2020-07-05 23:56 UTC
Labels: bug
